const LOCALE_KEY = 'gsa-locale'

export type Locale = 'fr' | 'en' | 'tr'

const labels: Record<Locale, string> = { fr: 'FR', en: 'EN', tr: 'TR' }
const flagEmoji: Record<Locale, string> = { fr: '🇫🇷', en: '🇬🇧', tr: '🇹🇷' }

const messages: Record<Locale, Record<string, string>> = {
  fr: {
    // Nav
    'nav.home': 'Accueil',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Prestation',
    'nav.about': 'À propos',
    'nav.login': 'Connexion',
    'nav.register': "S'inscrire",
    'nav.profile': 'Mon profil',
    'nav.shop': 'Ma boutique',
    'nav.downloads': 'Mes téléchargements',
    'nav.admin': 'Administration',
    'nav.logout': 'Déconnexion',
    'lang': 'Langue',
    // Footer
    'footer.tagline': 'GSA, un standard à venir.',
    'footer.platform': 'Plateforme',
    'footer.legal': 'Légal',
    'footer.cgv': 'CGV',
    'footer.privacy': 'Confidentialité',
    'footer.legal_notice': 'Mentions légales',
    'footer.support': 'Support',
    'footer.discord': 'Discord',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    // Hero
    'hero.title1': 'Des assets',
    'hero.title2': 'premium,',
    'hero.title3': 'prêts à déployer.',
    'hero.desc': 'Du mapping aux particules, GSA est pensé par un créateur pour les créateurs. Vérification humaine sur tous les produits.',
    'hero.explore': 'Explorer',
    'hero.assets': 'Assets',
    'hero.sales': 'Ventes',
    'hero.rating': 'Note',
    'hero.creators': 'Créateurs',
    'hero.themes': 'Thèmes',
    'hero.themes_sub': 'Dark RP · Médiéval · BaseWars · Manga',
    'hero.env': 'Environnement',
    'hero.env_sub': "Map & Props prêts à l'emploi",
    'hero.dev': 'Développement',
    'hero.dev_sub': 'Outils · Systèmes · SWEP',
    'hero.visual': 'Visuel',
    'hero.visual_sub': '3D models · Particules · Animation · UI',
    'hero.assets_verified': 'assets vérifiés',
    // Homepage
    'home.categories': 'Explorer par catégorie',
    'home.see_all': 'Tout voir',
    'home.browse_catalog': 'Parcourir le catalogue',
    'home.resources': 'ressources',
    'home.resource': 'ressource',
    'home.trending': 'Tendances',
    'home.promotions': 'Promotions',
    'home.collab_tag': 'COLLABORATEURS',
    'home.collab_title': 'Collaborateurs',
    'home.collab_desc': 'Des créateurs qui nous font confiance et proposent leurs services.',
    'home.collab_role': 'Collaborateur',
    'home.servers_tag': 'PROJETS',
    'home.servers_title': 'Nos clients',
    'home.servers_desc': 'Des projets qui utilisent et recommandent nos services.',
    'home.servers_role': 'Projet',
    'home.loading': 'Chargement…',
    'home.prev': 'Précédent',
    'home.next': 'Suivant',
    // Catalogue
    'cat.title': 'MARKETPLACE',
    'cat.subtitle': 'TOUT CE DONT TU AS BESOIN AU MÊME ENDROIT',
    'cat.search': 'Rechercher scripts, models, maps…',
    'cat.all': 'Tout',
    'cat.filters': 'Filtres',
    'cat.sort_by': 'Trier par',
    'cat.popular': 'Les plus populaires',
    'cat.newest': 'Plus récents',
    'cat.price_asc': 'Prix croissant',
    'cat.price_desc': 'Prix décroissant',
    'cat.rating': 'Mieux notés',
    'cat.discount': 'Promotions',
    'cat.trending': 'Tendances',
    'cat.max_price': 'Prix max.',
    'cat.options': 'Options',
    'cat.on_sale': 'En soldes seulement',
    'cat.verified': 'Vendeurs vérifiés',
    'cat.trending_only': 'Tendance seulement',
    'cat.min_rating': 'Note minimale',
    'cat.all_ratings': 'Toutes',
    'cat.reset': 'Réinitialiser',
    'cat.apply': 'Appliquer les filtres',
    'cat.no_results': 'Aucun résultat trouvé.',
    'cat.loading': 'Chargement…',
    'cat.new': 'NOUVEAU',
    'cat.seller': 'Vendeur',
    // About
    'about.title': 'À propos',
    'about.subtitle': 'GSA, pas une boutique, un standard.',
    'about.mission_title': 'Notre mission',
    'about.mission1': "GSA structure la distribution d'assets Garry's Mod, les prestations et l'accompagnement de projet dans un écosystème pensé pour les créateurs.",
    'about.mission2': "Les créateurs passent trop de temps sur l'aspect commercial au détriment de leur art. Les porteurs de projet galèrent à trouver des prestataires fiables. GSA résout ces deux problèmes en centralisant la distribution, la collaboration et le financement.",
    'about.list1': 'Mise en avant des assets de qualité',
    'about.list2': 'Gestion des paiements sécurisés',
    'about.list3': "Système de notation et d'avis vérifiés",
    'about.list4': 'Accompagnement des créateurs',
    'about.list5': 'Support client dédié',
    'about.nonexcl_title': 'Pourquoi la non exclusivité ?',
    'about.nonexcl_desc': "Nous croyons que les créateurs doivent pouvoir vendre où ils le souhaitent. GSA n'impose pas d'exclusivité, c'est un canal de vente supplémentaire, sans contrainte.",
    'about.nonexcl1': 'Liberté totale pour les créateurs',
    'about.nonexcl2': 'Aucun frais caché',
    'about.nonexcl3': 'Visibilité sur une marketplace dédiée',
    'about.nonexcl4': 'Communauté active et bienveillante',
    // Login
    'login.title': 'Connexion',
    'login.seller_sub': 'Espace dédié aux créateurs et vendeurs de la plateforme.',
    'login.admin_sub': 'Accès réservé aux administrateurs.',
    'login.submitting': 'Connexion…',
    'login.submit': 'Se connecter',
    'login.admin_error': "Compte administrateur, utilisez l'onglet Administrateur.",
    'login.seller_error': "Compte vendeur, utilisez l'onglet Vendeur.",
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.no_account': 'Pas de compte ?',
    'login.forgot': 'Mot de passe oublié ?',
    // Register
    'register.title': 'Créer un compte',
    'register.buyer': 'Acheteur',
    'register.buyer_sub': 'Accéder à la marketplace',
    'register.seller': 'Vendeur',
    'register.seller_sub': 'Vendre vos créations',
    'register.discord_linked': 'Compte Discord lié',
    'register.username': "Nom d'utilisateur",
    'register.email': 'Email',
    'register.password': 'Mot de passe',
    'register.intro': 'Présentez-vous',
    'register.intro_ph': 'Je suis développeur Lua depuis 5 ans…',
    'register.create_buyer': 'Créer mon compte',
    'register.create_seller': 'Créer mon compte vendeur',
    'register.success': 'Compte créé !',
    'register.has_account': 'Déjà un compte ?',
    'register.login_link': 'Se connecter',
    'register.cgv_accept': "J'accepte les conditions générales de vente",
    // Product
    'product.one_time': 'Paiement unique, accès à vie',
    'product.add_cart': 'Ajouter au panier',
    'product.buy_now': 'Acheter maintenant',
    'product.buy_now_label': 'Achat rapide',
    'product.in_cart': 'Dans le panier',
    'product.added_cart': 'Ajouté au panier',
    'product.owned': 'Déjà obtenu',
    'product.download': 'Télécharger',
    'product.already_cart': 'Déjà dans le panier',
    'product.support_6m': 'Support 6 mois',
    'product.verified': 'Vendeur vérifié',
    'product.features': 'Caractéristiques',
    'product.secure_payment': 'Paiement sécurisé',
    'product.instant_access': 'Accès immédiat',
    'product.gsa_protected': 'Protégé par GSA',
    'product.stripe_secure': 'Paiement sécurisé via Stripe',
    'product.lifetime_access': 'Accès à vie',
    'product.downloadable_updated': 'Téléchargeable et mis à jour',
    'product.documentation': 'Documentation',
    'product.install_guide': "Guide d'installation inclus",
    'product.support_incl': 'Support inclus',
    'product.support_desc': 'Assistance pendant 6 mois',
    'product.verified_item': 'Produit vérifié',
    'product.verified_desc': 'Testé et validé par notre équipe',
    'product.reviews': 'Avis',
    'product.reviews_empty': 'Aucun avis pour le moment.',
    'product.reviews_verified': 'Achat vérifié',
    'product.reviews_yours': 'Votre avis',
    'product.reviews_login': 'Connectez-vous pour laisser un avis.',
    'product.reviews_need_purchase': 'Achetez ce produit pour laisser un avis.',
    'product.reviews_write': 'Laissez un avis',
    'product.reviews_update_title': 'Modifiez votre avis',
    'product.reviews_placeholder': 'Partagez votre expérience avec ce produit...',
    'product.reviews_submit': 'Publier mon avis',
    'product.reviews_update': 'Mettre à jour mon avis',
    'product.reviews_delete': 'Supprimer',
    'product.reviews_delete_confirm_title': 'Supprimer mon avis',
    'product.reviews_delete_confirm': 'Voulez-vous vraiment supprimer votre avis ?',
    'product.reviews_submitted': 'Merci pour votre avis !',
    'product.reviews_updated': 'Avis mis à jour',
    'product.reviews_deleted': 'Avis supprimé',
    'product.reviews_error': 'Erreur lors de l\'envoi de l\'avis',
    // Cart
    'cart.title': 'Panier',
    'cart.secure': 'Paiement sécurisé · Livraison instantanée',
    'cart.empty': 'Votre panier est vide.',
    'cart.empty_sub': 'Découvrez nos produits et trouvez ce quil vous faut.',
    'cart.explore': 'Explorer la marketplace',
    'cart.summary': 'Récapitulatif',
    'cart.discount': 'Réduction',
    'cart.total': 'Total',
    'cart.checkout': 'Passer la commande',
    'cart.step1': 'Panier',
    'cart.step2': 'Paiement',
    'cart.step3': 'Terminé',
    'cart.success': 'Paiement réussi !',
    'cart.success_msg': 'Votre commande a été confirmée. Vous pouvez dès maintenant télécharger vos produits.',
    'cart.my_downloads': 'Mes téléchargements',
    'cart.pending': 'Votre paiement a bien été reçu, mais la confirmation prend quelques instants.',
    'cart.retry': 'Réessayer',
    'cart.see_downloads': 'Voir mes téléchargements',
    'cart.promo_placeholder': 'Code promo',
    'cart.promo_apply': 'Appliquer',
    'cart.promo_applied': 'Code appliqué !',
    'cart.promo_invalid': 'Code invalide ou expiré',
    'cart.remove': 'Retirer',
    // Downloads
    'downloads.loading': 'Chargement…',
    'downloads.title': 'Mes téléchargements',
    'downloads.subtitle': 'Retrouvez tous vos achats et téléchargez vos fichiers.',
    'downloads.none': 'Aucun téléchargement',
    'downloads.none_sub': "Vous n'avez encore rien acheté sur la marketplace.",
    'downloads.downloading': 'Téléchargement…',
    'downloads.download': 'Télécharger',
    'downloads.purchased': 'Acheté le',
    'downloads.retry': 'Réessayer',
    'downloads.auth_error': 'Vous devez être connecté pour voir vos achats.',
    'downloads.net_error': 'Erreur réseau, vérifiez votre connexion.',
    'downloads.srv_error': 'Erreur serveur, réessayez plus tard.',
    'downloads.dl_started': 'Téléchargement démarré ✓',
    'downloads.dl_error': 'Erreur de téléchargement',
    'downloads.pay_confirmed': 'Paiement confirmé !',
    'downloads.confirm_hint': 'Cliquez sur "Vérifier" pour confirmer le paiement',
    'downloads.order_confirmed': 'Commande confirmée !',
    'downloads.confirm_error': 'Erreur lors de la confirmation. Rafraîchissez la page.',
    'downloads.manual_title': 'Vous avez payé mais rien ne s\'affiche ?',
    'downloads.manual_sub': "Collez l'ID de session Stripe ici :",
    'downloads.processing': 'Confirmation en cours…',
    'downloads.pay_received': 'Paiement reçu !',
    'downloads.verify': 'Vérifier',
    'downloads.force_confirm': 'Forcer la confirmation',
    'downloads.invoice': 'Facture',
    'downloads.invoice_sub': 'Télécharger la facture de cette commande',
    'downloads.invoice_pdf': 'Facture (PDF)',
    'downloads.review_modal_title': 'Merci pour votre achat !',
    'downloads.review_modal_sub': 'Votre avis aide la communauté. Notez votre produit :',
    'downloads.review_modal_btn': 'Laisser un avis',
    'downloads.review_modal_later': 'Plus tard',
    // Prestation
    'prestation.title': 'Prestation',
    'prestation.consulting': 'Consulting & accompagnement',
    'prestation.consulting_desc': "De l'idée à la réalisation, je vous accompagne dans la conception et le développement de votre projet Garry's Mod.",
    'prestation.game_design': 'Game Design',
    'prestation.game_design_desc': 'Conception de mécaniques de jeu, équilibrage et optimisation pour garantir une expérience de qualité à vos joueurs.',
    'prestation.matchmaking': 'Mise en relation',
    'prestation.matchmaking_desc': "Vous avez besoin d'un développeur, d'un designer ou d'un asset spécifique ? Je vous mets en relation avec le bon prestataire.",
    'prestation.need_analysis': 'Analyse des besoins',
    'prestation.architecture': 'Architecture technique',
    'prestation.followup': 'Suivi et itérations',
    'prestation.documentation': 'Documentation complète',
    'prestation.mechanics': 'Mécaniques de jeu',
    'prestation.balance': 'Équilibrage économique',
    'prestation.progression': 'Progression et levelling',
    'prestation.testing': 'Tests et feedback',
    'prestation.devs': 'Développeurs qualifiés',
    'prestation.designers': 'Designers talentueux',
    'prestation.assets': 'Assets sur mesure',
    'prestation.guarantee': 'Garantie de qualité',
    // Seller account
    'seller.title': 'Espace vendeur',
    'seller.subtitle': 'Gérez votre profil et vos moyens de paiement.',
    'seller.profile': 'Profil',
    'seller.bio': 'Bio',
    'seller.bio_ph': 'Présentez votre travail…',
    'seller.save': 'Enregistrer',
    'seller.saved': 'Profil mis à jour !',
    'seller.linked': 'Comptes liés',
    'seller.discord_linked': 'Lié ✓',
    'seller.steam_linked': 'Lié ✓',
    'seller.stripe': 'Paiements',
    'seller.stripe_linked': 'Compte Stripe lié',
    'seller.stripe_unlinked': 'Stripe non connecté',
    'seller.stripe_checking': 'Vérification du compte Stripe…',
    'seller.stripe_ok': 'Compte Stripe connecté ✓',
    'seller.stripe_dashboard': 'Dashboard Stripe',
    'seller.connect_stripe': 'Connecter Stripe',
    'seller.bio_default': "Créateur de contenu pour Garry's Mod.",
    'seller.discord': 'Discord',
    'seller.steam': 'Steam',
    // Seller page
    'seller.verified': 'Vérifié',
    'seller.verified_by': 'Vérifié par GSA',
    'seller.products': 'Produits',
    'seller.no_products': 'Aucun produit pour le moment.',
    'seller.about': 'À propos',
    'seller.member_since': 'Membre depuis',
    'seller.discord_id_copied': 'Discord ID copié !',
    'seller.link_copied': 'Lien copié !',
    'seller.no_bio': 'Pas de description.',
    // Generic
    'generic.loading': 'Chargement…',
    'generic.error': 'Erreur',
    'generic.cancel': 'Annuler',
    'generic.save': 'Enregistrer',
    'generic.close': 'Fermer',
    'generic.back': 'Retour',
    'generic.copied': 'Copié !',
  },
  en: {
    'nav.home': 'Home',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.login': 'Sign in',
    'nav.register': 'Sign up',
    'nav.profile': 'My profile',
    'nav.shop': 'My shop',
    'downloads.loading': 'Loading…',
    'nav.downloads': 'My downloads',
    'nav.admin': 'Administration',
    'nav.logout': 'Log out',
    'lang': 'Language',
    'footer.tagline': 'GSA, a standard to come.',
    'footer.platform': 'Platform',
    'footer.legal': 'Legal',
    'footer.cgv': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.legal_notice': 'Legal notice',
    'footer.support': 'Support',
    'footer.discord': 'Discord',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'hero.title1': 'Premium',
    'hero.title2': 'assets,',
    'hero.title3': 'ready to deploy.',
    'hero.desc': 'From mapping to particles — GSA is built by a creator, for creators. Human verification on every product.',
    'hero.explore': 'Explore',
    'hero.assets': 'Assets',
    'hero.sales': 'Sales',
    'hero.rating': 'Rating',
    'hero.creators': 'Creators',
    'hero.themes': 'Themes',
    'hero.themes_sub': 'Dark RP · Medieval · BaseWars · Manga',
    'hero.env': 'Environment',
    'hero.env_sub': 'Ready-to-use Maps & Props',
    'hero.dev': 'Development',
    'hero.dev_sub': 'Tools · Systems · SWEP',
    'hero.visual': 'Visual',
    'hero.visual_sub': '3D models · Particles · Animation · UI',
    'hero.assets_verified': 'verified assets',
    'home.categories': 'Browse by category',
    'home.see_all': 'See all',
    'home.browse_catalog': 'Browse catalog',
    'home.resources': 'resources',
    'home.resource': 'resource',
    'home.trending': 'Trending',
    'home.promotions': 'Promotions',
    'home.collab_tag': 'COLLABORATORS',
    'home.collab_title': 'Collaborators',
    'home.collab_desc': 'Creators who trust us and offer their services.',
    'home.collab_role': 'Collaborator',
    'home.servers_tag': 'PROJECTS',
    'home.servers_title': 'Our clients',
    'home.servers_desc': 'Projects that use and recommend our services.',
    'home.servers_role': 'Project',
    'home.loading': 'Loading…',
    'home.prev': 'Previous',
    'home.next': 'Next',
    'cat.title': 'MARKETPLACE',
    'cat.subtitle': 'EVERYTHING YOU NEED IN ONE PLACE',
    'cat.search': 'Search scripts, models, maps…',
    'cat.all': 'All',
    'cat.filters': 'Filters',
    'cat.sort_by': 'Sort by',
    'cat.popular': 'Most popular',
    'cat.newest': 'Newest',
    'cat.price_asc': 'Price: low to high',
    'cat.price_desc': 'Price: high to low',
    'cat.rating': 'Top rated',
    'cat.discount': 'Promotions',
    'cat.trending': 'Trending',
    'cat.max_price': 'Max price',
    'cat.options': 'Options',
    'cat.on_sale': 'On sale only',
    'cat.verified': 'Verified sellers',
    'cat.trending_only': 'Trending only',
    'cat.min_rating': 'Minimum rating',
    'cat.all_ratings': 'All',
    'cat.reset': 'Reset',
    'cat.apply': 'Apply filters',
    'cat.no_results': 'No results found.',
    'cat.loading': 'Loading…',
    'cat.new': 'NEW',
    'cat.seller': 'Seller',
    'about.title': 'About',
    'about.subtitle': 'GSA, not a shop, a standard.',
    'about.mission_title': 'Our mission',
    'about.mission1': "GSA structures Garry's Mod asset distribution, services and project support in an ecosystem designed for creators.",
    'about.mission2': "Creators spend too much time on the business side at the expense of their art. Project owners struggle to find reliable freelancers. GSA solves both by centralizing distribution, collaboration and funding.",
    'about.list1': 'Showcasing quality assets',
    'about.list2': 'Secure payment handling',
    'about.list3': 'Verified rating and review system',
    'about.list4': 'Creator support',
    'about.list5': 'Dedicated customer support',
    'about.nonexcl_title': 'Why no exclusivity?',
    'about.nonexcl_desc': "We believe creators should be able to sell wherever they want. GSA doesn't impose exclusivity — it's an additional sales channel, no strings attached.",
    'about.nonexcl1': 'Total freedom for creators',
    'about.nonexcl2': 'No hidden fees',
    'about.nonexcl3': 'Visibility on a dedicated marketplace',
    'about.nonexcl4': 'Active and supportive community',
    'login.title': 'Sign in',
    'login.seller_sub': 'Dedicated space for creators and sellers on the platform.',
    'login.admin_sub': 'Restricted access for administrators.',
    'login.submitting': 'Signing in…',
    'login.submit': 'Sign in',
    'login.admin_error': 'Admin account, please use the Admin tab.',
    'login.seller_error': 'Seller account, please use the Seller tab.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.no_account': "Don't have an account?",
    'login.forgot': 'Forgot password?',
    'register.title': 'Create account',
    'register.buyer': 'Buyer',
    'register.buyer_sub': 'Access the marketplace',
    'register.seller': 'Seller',
    'register.seller_sub': 'Sell your creations',
    'register.discord_linked': 'Discord account linked',
    'register.username': 'Username',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.intro': 'Introduce yourself',
    'register.intro_ph': 'I have been a Lua developer for 5 years…',
    'register.create_buyer': 'Create account',
    'register.create_seller': 'Create seller account',
    'register.success': 'Account created!',
    'register.has_account': 'Already have an account?',
    'register.login_link': 'Sign in',
    'register.cgv_accept': 'I accept the terms and conditions',
    'product.one_time': 'One-time payment, lifetime access',
    'product.add_cart': 'Add to cart',
    'product.buy_now': 'Buy now',
    'product.in_cart': 'In cart',
    'product.added_cart': 'Added to cart',
    'product.owned': 'Already owned',
    'product.download': 'Download',
    'product.already_cart': 'Already in cart',
    'product.support_6m': '6-month support',
    'product.verified': 'Verified seller',
    'product.features': 'Features',
    'product.secure_payment': 'Secure payment',
    'product.instant_access': 'Instant access',
    'product.gsa_protected': 'Protected by GSA',
    'product.stripe_secure': 'Secure payment via Stripe',
    'product.lifetime_access': 'Lifetime access',
    'product.downloadable_updated': 'Downloadable & updated',
    'product.documentation': 'Documentation',
    'product.install_guide': 'Installation guide included',
    'product.support_incl': 'Support included',
    'product.support_desc': '6-month assistance',
    'product.verified_item': 'Verified product',
    'product.verified_desc': 'Tested and validated by our team',
    'product.reviews': 'Reviews',
    'product.reviews_empty': 'No reviews yet.',
    'product.reviews_verified': 'Verified purchase',
    'product.reviews_yours': 'Your review',
    'product.reviews_login': 'Log in to leave a review.',
    'product.reviews_need_purchase': 'Purchase this product to leave a review.',
    'product.reviews_write': 'Leave a review',
    'product.reviews_update_title': 'Update your review',
    'product.reviews_placeholder': 'Share your experience with this product...',
    'product.reviews_submit': 'Submit review',
    'product.reviews_update': 'Update my review',
    'product.reviews_delete': 'Delete',
    'product.reviews_delete_confirm_title': 'Delete my review',
    'product.reviews_delete_confirm': 'Are you sure you want to delete your review?',
    'product.reviews_submitted': 'Thanks for your review!',
    'product.reviews_updated': 'Review updated',
    'product.reviews_deleted': 'Review deleted',
    'product.reviews_error': 'Error submitting review',
    'cart.title': 'Cart',
    'cart.secure': 'Secure payment · Instant delivery',
    'cart.empty': 'Your cart is empty.',
    'cart.empty_sub': 'Discover our products and find what you need.',
    'cart.explore': 'Browse marketplace',
    'cart.summary': 'Summary',
    'cart.discount': 'Discount',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.step1': 'Cart',
    'cart.step2': 'Payment',
    'cart.step3': 'Done',
    'cart.success': 'Payment successful!',
    'cart.success_msg': 'Your order has been confirmed. You can now download your products.',
    'cart.my_downloads': 'My downloads',
    'cart.pending': 'Your payment was received, but confirmation is taking a moment.',
    'cart.retry': 'Retry',
    'cart.see_downloads': 'See my downloads',
    'cart.promo_placeholder': 'Promo code',
    'cart.promo_apply': 'Apply',
    'cart.promo_applied': 'Code applied!',
    'cart.promo_invalid': 'Invalid or expired code',
    'cart.remove': 'Remove',
    'downloads.title': 'My downloads',
    'downloads.subtitle': 'Find all your purchases and download your files.',
    'downloads.none': 'No downloads',
    'downloads.none_sub': "You haven't purchased anything on the marketplace yet.",
    'downloads.downloading': 'Downloading…',
    'downloads.download': 'Download',
    'downloads.purchased': 'Purchased on',
    'downloads.retry': 'Retry',
    'downloads.auth_error': 'You must be logged in to see your purchases.',
    'downloads.net_error': 'Network error, check your connection.',
    'downloads.srv_error': 'Server error, try again later.',
    'downloads.dl_started': 'Download started ✓',
    'downloads.dl_error': 'Download error',
    'downloads.pay_confirmed': 'Payment confirmed!',
    'downloads.confirm_hint': 'Click "Verify" to confirm payment',
    'downloads.order_confirmed': 'Order confirmed!',
    'downloads.confirm_error': 'Confirmation error. Refresh the page.',
    'downloads.manual_title': 'You paid but nothing shows up?',
    'downloads.manual_sub': 'Paste your Stripe session ID here:',
    'downloads.processing': 'Confirming…',
    'downloads.pay_received': 'Payment received!',
    'downloads.verify': 'Verify',
    'downloads.force_confirm': 'Force confirmation',
    'downloads.invoice': 'Invoice',
    'downloads.invoice_sub': 'Download the invoice for this order',
    'downloads.invoice_pdf': 'Invoice (PDF)',
    'downloads.review_modal_title': 'Thanks for your purchase!',
    'downloads.review_modal_sub': 'Your review helps the community. Rate your product:',
    'downloads.review_modal_btn': 'Leave a review',
    'downloads.review_modal_later': 'Later',
    'prestation.title': 'Services',
    'prestation.consulting': 'Consulting & support',
    'prestation.consulting_desc': "From idea to completion, I support you in designing and developing your Garry's Mod project.",
    'prestation.game_design': 'Game Design',
    'prestation.game_design_desc': 'Game mechanics design, balancing and optimization to ensure a quality experience for your players.',
    'prestation.matchmaking': 'Matchmaking',
    'prestation.matchmaking_desc': 'Need a developer, designer or a specific asset? I connect you with the right freelancer.',
    'prestation.need_analysis': 'Needs analysis',
    'prestation.architecture': 'Technical architecture',
    'prestation.followup': 'Follow-up & iterations',
    'prestation.documentation': 'Full documentation',
    'prestation.mechanics': 'Game mechanics',
    'prestation.balance': 'Economic balance',
    'prestation.progression': 'Progression & leveling',
    'prestation.testing': 'Testing & feedback',
    'prestation.devs': 'Qualified developers',
    'prestation.designers': 'Talented designers',
    'prestation.assets': 'Custom assets',
    'prestation.guarantee': 'Quality guarantee',
    'seller.title': 'Seller dashboard',
    'seller.subtitle': 'Manage your profile and payment methods.',
    'seller.profile': 'Profile',
    'seller.bio': 'Bio',
    'seller.bio_ph': 'Describe your work…',
    'seller.save': 'Save',
    'seller.saved': 'Profile updated!',
    'seller.linked': 'Linked accounts',
    'seller.discord_linked': 'Linked ✓',
    'seller.steam_linked': 'Linked ✓',
    'seller.stripe': 'Payments',
    'seller.stripe_linked': 'Stripe account linked',
    'seller.stripe_unlinked': 'Stripe not connected',
    'seller.stripe_checking': 'Checking Stripe account…',
    'seller.stripe_ok': 'Stripe account connected ✓',
    'seller.stripe_dashboard': 'Stripe Dashboard',
    'seller.connect_stripe': 'Connect Stripe',
    'seller.bio_default': "Garry's Mod content creator.",
    'seller.discord': 'Discord',
    'seller.steam': 'Steam',
    'seller.verified': 'Verified',
    'seller.verified_by': 'Verified by GSA',
    'seller.products': 'Products',
    'seller.no_products': 'No products yet.',
    'seller.about': 'About',
    'seller.member_since': 'Member since',
    'seller.discord_id_copied': 'Discord ID copied!',
    'seller.link_copied': 'Link copied!',
    'seller.no_bio': 'No description.',
    'generic.loading': 'Loading…',
    'generic.error': 'Error',
    'generic.cancel': 'Cancel',
    'generic.save': 'Save',
    'generic.close': 'Close',
    'generic.back': 'Back',
    'generic.copied': 'Copied!',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.marketplace': 'Market',
    'nav.services': 'Hizmetler',
    'nav.about': 'Hakkımızda',
    'nav.login': 'Giriş',
    'nav.register': 'Kayıt Ol',
    'nav.profile': 'Profilim',
    'nav.shop': 'Mağazam',
    'nav.downloads': 'İndirdiklerim',
    'nav.admin': 'Yönetim',
    'nav.logout': 'Çıkış',
    'lang': 'Dil',
    'footer.tagline': 'GSA, gelecek bir standart.',
    'footer.platform': 'Platform',
    'footer.legal': 'Yasal',
    'footer.cgv': 'Şartlar',
    'footer.privacy': 'Gizlilik',
    'footer.legal_notice': 'Yasal bildirim',
    'footer.support': 'Destek',
    'footer.discord': 'Discord',
    'footer.contact': 'İletişim',
    'footer.rights': 'Tüm hakları saklıdır.',
    'hero.title1': 'Premium',
    'hero.title2': 'assetler,',
    'hero.title3': 'kullanıma hazır.',
    'hero.desc': "Mapping'den partiküllere — GSA, yaratıcılar için bir yaratıcı tarafından tasarlandı. Her üründe insan doğrulaması.",
    'hero.explore': 'Keşfet',
    'hero.assets': 'Assetler',
    'hero.sales': 'Satışlar',
    'hero.rating': 'Puan',
    'hero.creators': 'Yaratıcılar',
    'hero.themes': 'Temalar',
    'hero.themes_sub': 'Dark RP · Ortaçağ · BaseWars · Manga',
    'hero.env': 'Çevre',
    'hero.env_sub': 'Kullanıma hazır Map & Prop',
    'hero.dev': 'Geliştirme',
    'hero.dev_sub': 'Araçlar · Sistemler · SWEP',
    'hero.visual': 'Görsel',
    'hero.visual_sub': '3D modeller · Partiküller · Animasyon · UI',
    'hero.assets_verified': 'doğrulanmış asset',
    'home.categories': 'Kategoriye göre keşfet',
    'home.see_all': 'Tümünü gör',
    'home.browse_catalog': 'Kataloğa göz at',
    'home.resources': 'kaynak',
    'home.resource': 'kaynak',
    'home.trending': 'Trendler',
    'home.promotions': 'Promosyonlar',
    'home.collab_tag': 'İŞBİRLİKÇİLER',
    'home.collab_title': 'İşbirlikçiler',
    'home.collab_desc': 'Bize güvenen ve hizmetlerini sunan yaratıcılar.',
    'home.collab_role': 'İşbirlikçi',
    'home.servers_tag': 'PROJELER',
    'home.servers_title': 'Müşterilerimiz',
    'home.servers_desc': 'Hizmetlerimizi kullanan ve öneren projeler.',
    'home.servers_role': 'Proje',
    'home.loading': 'Yükleniyor…',
    'home.prev': 'Önceki',
    'home.next': 'Sonraki',
    'cat.title': 'MARKET',
    'cat.subtitle': 'İHTİYACIN OLAN HER ŞEY TEK YERDE',
    'cat.search': 'Script, model, map ara…',
    'cat.all': 'Tümü',
    'cat.filters': 'Filtreler',
    'cat.sort_by': 'Sırala',
    'cat.popular': 'En popüler',
    'cat.newest': 'En yeni',
    'cat.price_asc': 'Fiyat: düşükten yükseğe',
    'cat.price_desc': 'Fiyat: yüksekten düşüğe',
    'cat.rating': 'En çok oy alan',
    'cat.discount': 'Promosyonlar',
    'cat.trending': 'Trendler',
    'cat.max_price': 'Maks. fiyat',
    'cat.options': 'Seçenekler',
    'cat.on_sale': 'Sadece indirimdekiler',
    'cat.verified': 'Doğrulanmış satıcılar',
    'cat.trending_only': 'Sadece trendler',
    'cat.min_rating': 'Minimum puan',
    'cat.all_ratings': 'Tümü',
    'cat.reset': 'Sıfırla',
    'cat.apply': 'Filtreleri uygula',
    'cat.no_results': 'Sonuç bulunamadı.',
    'cat.loading': 'Yükleniyor…',
    'cat.new': 'YENİ',
    'cat.seller': 'Satıcı',
    'about.title': 'Hakkımızda',
    'about.subtitle': 'GSA, bir dükkan değil, bir standart.',
    'about.mission_title': 'Misyonumuz',
    'about.mission1': "GSA, Garry's Mod asset dağıtımını, hizmetleri ve proje desteğini yaratıcılar için tasarlanmış bir ekosistemde yapılandırır.",
    'about.mission2': 'Yaratıcılar sanatları pahasına iş tarafında çok fazla zaman harcıyor. Proje sahipleri güvenilir freelancer bulmakta zorlanıyor. GSA dağıtımı, işbirliğini ve finansmanı merkezileştirerek her ikisini de çözer.',
    'about.list1': 'Kaliteli assetleri öne çıkarma',
    'about.list2': 'Güvenli ödeme yönetimi',
    'about.list3': 'Doğrulanmış puan ve yorum sistemi',
    'about.list4': 'Yaratıcı desteği',
    'about.list5': 'Özel müşteri desteği',
    'about.nonexcl_title': 'Neden münhasır olmayan?',
    'about.nonexcl_desc': 'Yaratıcıların istedikleri yerde satış yapabilmeleri gerektiğine inanıyoruz. GSA münhasırlık dayatmaz — ek bir satış kanalıdır, hiçbir bağlayıcılık yoktur.',
    'about.nonexcl1': 'Yaratıcılar için tam özgürlük',
    'about.nonexcl2': 'Gizli ücret yok',
    'about.nonexcl3': 'Özel bir markette görünürlük',
    'about.nonexcl4': 'Aktif ve destekleyici topluluk',
    'login.title': 'Giriş',
    'login.seller_sub': 'Platformdaki yaratıcılar ve satıcılar için özel alan.',
    'login.admin_sub': 'Yöneticilere özel erişim.',
    'login.submitting': 'Giriş yapılıyor…',
    'login.submit': 'Giriş yap',
    'login.admin_error': 'Yönetici hesabı, lütfen Yönetici sekmesini kullanın.',
    'login.seller_error': 'Satıcı hesabı, lütfen Satıcı sekmesini kullanın.',
    'login.email': 'E-posta',
    'login.password': 'Şifre',
    'login.no_account': 'Hesabınız yok mu?',
    'login.forgot': 'Şifrenizi mi unuttunuz?',
    'register.title': 'Hesap oluştur',
    'register.buyer': 'Alıcı',
    'register.buyer_sub': 'Markete eriş',
    'register.seller': 'Satıcı',
    'register.seller_sub': 'Kreasyonlarını sat',
    'register.discord_linked': 'Discord hesabı bağlı',
    'register.username': 'Kullanıcı adı',
    'register.email': 'E-posta',
    'register.password': 'Şifre',
    'register.intro': 'Kendini tanıt',
    'register.intro_ph': '5 yıldır Lua geliştiricisiyim…',
    'register.create_buyer': 'Hesap oluştur',
    'register.create_seller': 'Satıcı hesabı oluştur',
    'register.success': 'Hesap oluşturuldu!',
    'register.has_account': 'Zaten hesabınız var mı?',
    'register.login_link': 'Giriş yap',
    'register.cgv_accept': 'Şartlar ve koşulları kabul ediyorum',
    'product.one_time': 'Tek seferlik ödeme, ömür boyu erişim',
    'product.add_cart': 'Sepete ekle',
    'product.buy_now': 'Hemen al',
    'product.in_cart': 'Sepette',
    'product.added_cart': 'Sepete eklendi',
    'product.owned': 'Zaten sahip olundu',
    'product.download': 'İndir',
    'product.already_cart': 'Zaten sepette',
    'product.support_6m': '6 ay destek',
    'product.verified': 'Doğrulanmış satıcı',
    'product.features': 'Özellikler',
    'product.secure_payment': 'Güvenli ödeme',
    'product.instant_access': 'Anında erişim',
    'product.gsa_protected': 'GSA tarafından korunuyor',
    'product.stripe_secure': 'Stripe ile güvenli ödeme',
    'product.lifetime_access': 'Ömür boyu erişim',
    'product.downloadable_updated': 'İndirilebilir ve güncel',
    'product.documentation': 'Dokümantasyon',
    'product.install_guide': 'Kurulum kılavuzu dahil',
    'product.support_incl': 'Destek dahil',
    'product.support_desc': '6 ay yardım',
    'product.verified_item': 'Doğrulanmış ürün',
    'product.verified_desc': 'Ekibimiz tarafından test edildi ve onaylandı',
    'product.reviews': 'Yorumlar',
    'product.reviews_empty': 'Henüz yorum yok.',
    'product.reviews_verified': 'Doğrulanmış satın alma',
    'product.reviews_yours': 'Yorumunuz',
    'product.reviews_login': 'Yorum bırakmak için giriş yapın.',
    'product.reviews_need_purchase': 'Yorum bırakmak için bu ürünü satın alın.',
    'product.reviews_write': 'Yorum bırakın',
    'product.reviews_update_title': 'Yorumunuzu güncelleyin',
    'product.reviews_placeholder': 'Bu ürünle ilgili deneyiminizi paylaşın...',
    'product.reviews_submit': 'Yorumu gönder',
    'product.reviews_update': 'Yorumumu güncelle',
    'product.reviews_delete': 'Sil',
    'product.reviews_delete_confirm_title': 'Yorumumu sil',
    'product.reviews_delete_confirm': 'Yorumunuzu silmek istediğinize emin misiniz?',
    'product.reviews_submitted': 'Yorumunuz için teşekkürler!',
    'product.reviews_updated': 'Yorum güncellendi',
    'product.reviews_deleted': 'Yorum silindi',
    'product.reviews_error': 'Yorum gönderilirken hata oluştu',
    'cart.title': 'Sepet',
    'cart.secure': 'Güvenli ödeme · Anında teslimat',
    'cart.empty': 'Sepetiniz boş.',
    'cart.empty_sub': 'Ürünlerimizi keşfedin ve ihtiyacınız olanı bulun.',
    'cart.explore': 'Markete göz at',
    'cart.summary': 'Özet',
    'cart.discount': 'İndirim',
    'cart.total': 'Toplam',
    'cart.checkout': 'Ödemeye geç',
    'cart.step1': 'Sepet',
    'cart.step2': 'Ödeme',
    'cart.step3': 'Tamam',
    'cart.success': 'Ödeme başarılı!',
    'cart.success_msg': 'Siparişiniz onaylandı. Ürünlerinizi şimdi indirebilirsiniz.',
    'cart.my_downloads': 'İndirdiklerim',
    'cart.pending': 'Ödemeniz alındı, ancak onay biraz zaman alıyor.',
    'cart.retry': 'Tekrar dene',
    'cart.see_downloads': 'İndirdiklerimi gör',
    'cart.promo_placeholder': 'Promosyon kodu',
    'cart.promo_apply': 'Uygula',
    'cart.promo_applied': 'Kod uygulandı!',
    'cart.promo_invalid': 'Geçersiz veya süresi dolmuş kod',
    'cart.remove': 'Kaldır',
    'downloads.loading': 'Yükleniyor…',
    'downloads.title': 'İndirdiklerim',
    'downloads.subtitle': 'Tüm satın almalarınızı bulun ve dosyalarınızı indirin.',
    'downloads.none': 'İndirme yok',
    'downloads.none_sub': 'Henüz marketten hiçbir şey satın almadınız.',
    'downloads.downloading': 'İndiriliyor…',
    'downloads.download': 'İndir',
    'downloads.purchased': 'Satın alma tarihi',
    'downloads.retry': 'Tekrar dene',
    'downloads.auth_error': 'Satın almalarınızı görmek için giriş yapmalısınız.',
    'downloads.net_error': 'Ağ hatası, bağlantınızı kontrol edin.',
    'downloads.srv_error': 'Sunucu hatası, daha sonra tekrar deneyin.',
    'downloads.dl_started': 'İndirme başladı ✓',
    'downloads.dl_error': 'İndirme hatası',
    'downloads.pay_confirmed': 'Ödeme onaylandı!',
    'downloads.confirm_hint': 'Ödemeyi onaylamak için "Doğrula"ya tıklayın',
    'downloads.order_confirmed': 'Sipariş onaylandı!',
    'downloads.confirm_error': 'Onay hatası. Sayfayı yenileyin.',
    'downloads.manual_title': 'Ödediniz ama hiçbir şey görünmüyor mu?',
    'downloads.manual_sub': 'Stripe oturum ID\'nizi buraya yapıştırın:',
    'downloads.processing': 'Onaylanıyor…',
    'downloads.pay_received': 'Ödeme alındı!',
    'downloads.verify': 'Doğrula',
    'downloads.force_confirm': 'Onayı zorla',
    'downloads.invoice': 'Fatura',
    'downloads.invoice_sub': 'Bu siparişin faturasını indir',
    'downloads.invoice_pdf': 'Fatura (PDF)',
    'downloads.review_modal_title': 'Satın aldığınız için teşekkürler!',
    'downloads.review_modal_sub': 'Yorumunuz topluluğa yardımcı olur. Ürününüzü değerlendirin:',
    'downloads.review_modal_btn': 'Yorum bırak',
    'downloads.review_modal_later': 'Sonra',
    'prestation.title': 'Hizmetler',
    'prestation.consulting': 'Danışmanlık & destek',
    'prestation.consulting_desc': "Fikirden tamamlamaya, Garry's Mod projenizin tasarımı ve geliştirilmesinde size destek oluyorum.",
    'prestation.game_design': 'Oyun Tasarımı',
    'prestation.game_design_desc': 'Oyuncularınıza kaliteli bir deneyim sunmak için oyun mekaniği tasarımı, dengeleme ve optimizasyon.',
    'prestation.matchmaking': 'Eşleştirme',
    'prestation.matchmaking_desc': 'Bir geliştiriciye, tasarımcıya veya belirli bir asset\'e mi ihtiyacınız var? Sizi doğru freelancer ile buluşturuyorum.',
    'prestation.need_analysis': 'İhtiyaç analizi',
    'prestation.architecture': 'Teknik mimari',
    'prestation.followup': 'Takip & iterasyonlar',
    'prestation.documentation': 'Tam dokümantasyon',
    'prestation.mechanics': 'Oyun mekanikleri',
    'prestation.balance': 'Ekonomik denge',
    'prestation.progression': 'İlerleme & seviye',
    'prestation.testing': 'Test & geri bildirim',
    'prestation.devs': 'Nitelikli geliştiriciler',
    'prestation.designers': 'Yetenekli tasarımcılar',
    'prestation.assets': 'Özel assetler',
    'prestation.guarantee': 'Kalite garantisi',
    'seller.title': 'Satıcı Paneli',
    'seller.subtitle': 'Profilinizi ve ödeme yöntemlerinizi yönetin.',
    'seller.profile': 'Profil',
    'seller.bio': 'Biyografi',
    'seller.bio_ph': 'Çalışmanızı tanıtın…',
    'seller.save': 'Kaydet',
    'seller.saved': 'Profil güncellendi!',
    'seller.linked': 'Bağlı hesaplar',
    'seller.discord_linked': 'Bağlı ✓',
    'seller.steam_linked': 'Bağlı ✓',
    'seller.stripe': 'Ödemeler',
    'seller.stripe_linked': 'Stripe hesabı bağlı',
    'seller.stripe_unlinked': 'Stripe bağlı değil',
    'seller.stripe_checking': 'Stripe hesabı kontrol ediliyor…',
    'seller.stripe_ok': 'Stripe hesabı bağlı ✓',
    'seller.stripe_dashboard': 'Stripe Dashboard',
    'seller.connect_stripe': 'Stripe\'a bağlan',
    'seller.bio_default': "Garry's Mod içerik yaratıcısı.",
    'seller.discord': 'Discord',
    'seller.steam': 'Steam',
    'seller.verified': 'Doğrulandı',
    'seller.verified_by': 'GSA tarafından doğrulandı',
    'seller.products': 'Ürünler',
    'seller.no_products': 'Henüz ürün yok.',
    'seller.about': 'Hakkında',
    'seller.member_since': 'Üyelik tarihi',
    'seller.discord_id_copied': 'Discord ID kopyalandı!',
    'seller.link_copied': 'Bağlantı kopyalandı!',
    'seller.no_bio': 'Açıklama yok.',
    'generic.loading': 'Yükleniyor…',
    'generic.error': 'Hata',
    'generic.cancel': 'İptal',
    'generic.save': 'Kaydet',
    'generic.close': 'Kapat',
    'generic.back': 'Geri',
    'generic.copied': 'Kopyalandı!',
  },
}

const locale = ref<Locale>('fr')

function initLocale() {
  if (typeof window !== 'undefined') {
    const saved = localStorage.getItem(LOCALE_KEY) as Locale | null
    if (saved && ['fr', 'en', 'tr'].includes(saved)) {
      locale.value = saved
    }
  }
}

function setLocale(l: Locale) {
  locale.value = l
  localStorage.setItem(LOCALE_KEY, l)
}

function t(key: string, fallback?: string): string {
  return messages[locale.value]?.[key] ?? fallback ?? key
}

export function useLang() {
  return { locale, labels, flagEmoji, initLocale, setLocale, t }
}
