const LOCALE_KEY = 'gsa-locale'

export type Locale = 'fr' | 'en'

const labels: Record<Locale, string> = { fr: 'FR', en: 'EN' }
const flagEmoji: Record<Locale, string> = { fr: '🇫🇷', en: '🇬🇧' }

const messages: Record<Locale, Record<string, string>> = {
  fr: {
    // Nav
    'nav.home': 'Accueil',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Prestation',
    'nav.about': 'À propos',
    'nav.login': 'Connexion',
    'nav.register': "S'inscrire",
    'nav.profile': 'Mon profil',
    'nav.shop': 'Ma boutique',
    'nav.downloads': 'Mes téléchargements',
    'nav.admin': 'Administration',
    'nav.logout': 'Déconnexion',
    'lang': 'Langue',
    // Footer
    'footer.tagline': 'GSA, un standard à venir.',
    'footer.platform': 'Plateforme',
    'footer.legal': 'Légal',
    'footer.cgv': 'CGV',
    'footer.privacy': 'Confidentialité',
    'footer.legal_notice': 'Mentions légales',
    'footer.support': 'Support',
    'footer.discord': 'Discord',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    // Hero
    'hero.title1': 'Des assets',
    'hero.title2': 'premium,',
    'hero.title3': 'prêts à déployer.',
    'hero.desc': 'Du mapping aux particules, GSA est pensé par un créateur pour les créateurs. Vérification humaine sur tous les produits.',
    'hero.explore': 'Explorer',
    'hero.assets': 'Assets',
    'hero.sales': 'Ventes',
    'hero.rating': 'Note',
    'hero.creators': 'Créateurs',
    'hero.themes': 'Thèmes',
    'hero.themes_sub': 'Dark RP · Médiéval · BaseWars · Manga',
    'hero.env': 'Environnement',
    'hero.env_sub': "Map & Props prêts à l'emploi",
    'hero.dev': 'Développement',
    'hero.dev_sub': 'Outils · Systèmes · SWEP',
    'hero.visual': 'Visuel',
    'hero.visual_sub': '3D models · Particules · Animation · UI',
    'hero.assets_verified': 'assets vérifiés',
    // Homepage
    'home.categories': 'Explorer par catégorie',
    'home.see_all': 'Tout voir',
    'home.browse_catalog': 'Parcourir le catalogue',
    'home.resources': 'ressources',
    'home.resource': 'ressource',
    'home.trending': 'Tendances',
    'home.promotions': 'Promotions',
    'home.collab_tag': 'COLLABORATEURS',
    'home.collab_title': 'Collaborateurs',
    'home.collab_desc': 'Des créateurs qui nous font confiance et proposent leurs services.',
    'home.collab_role': 'Collaborateur',
    'home.servers_tag': 'PROJETS',
    'home.servers_title': 'Nos clients',
    'home.servers_desc': 'Des projets qui utilisent et recommandent nos services.',
    'home.servers_role': 'Projet',
    'home.loading': 'Chargement…',
    'home.prev': 'Précédent',
    'home.next': 'Suivant',
    // Catalogue
    'cat.title': 'MARKETPLACE',
    'cat.subtitle': 'TOUT CE DONT TU AS BESOIN AU MÊME ENDROIT',
    'cat.search': 'Rechercher scripts, models, maps…',
    'cat.all': 'Tout',
    'cat.filters': 'Filtres',
    'cat.sort_by': 'Trier par',
    'cat.popular': 'Les plus populaires',
    'cat.newest': 'Plus récents',
    'cat.price_asc': 'Prix croissant',
    'cat.price_desc': 'Prix décroissant',
    'cat.rating': 'Mieux notés',
    'cat.discount': 'Promotions',
    'cat.trending': 'Tendances',
    'cat.max_price': 'Prix max.',
    'cat.options': 'Options',
    'cat.on_sale': 'En soldes seulement',
    'cat.verified': 'Vendeurs vérifiés',
    'cat.trending_only': 'Tendance seulement',
    'cat.min_rating': 'Note minimale',
    'cat.all_ratings': 'Toutes',
    'cat.reset': 'Réinitialiser',
    'cat.apply': 'Appliquer les filtres',
    'cat.no_results': 'Aucun résultat trouvé.',
    'cat.loading': 'Chargement…',
    'cat.new': 'NOUVEAU',
    'cat.seller': 'Vendeur',
    // About
    'about.title': 'À propos',
    'about.subtitle': 'GSA, pas une boutique, un standard.',
    'about.mission_title': 'Notre mission',
    'about.mission1': "GSA structure la distribution d'assets Garry's Mod, les prestations et l'accompagnement de projet dans un écosystème pensé pour les créateurs.",
    'about.mission2': "Les créateurs passent trop de temps sur l'aspect commercial au détriment de leur art. Les porteurs de projet galèrent à trouver des prestataires fiables. GSA résout ces deux problèmes en centralisant la distribution, la collaboration et le financement.",
    'about.list1': 'Mise en avant des assets de qualité',
    'about.list2': 'Gestion des paiements sécurisés',
    'about.list3': "Système de notation et d'avis vérifiés",
    'about.list4': 'Accompagnement des créateurs',
    'about.list5': 'Support client dédié',
    'about.nonexcl_title': 'Pourquoi la non exclusivité ?',
    'about.nonexcl_desc': "Nous croyons que les créateurs doivent pouvoir vendre où ils le souhaitent. GSA n'impose pas d'exclusivité, c'est un canal de vente supplémentaire, sans contrainte.",
    'about.nonexcl1': 'Liberté totale pour les créateurs',
    'about.nonexcl2': 'Aucun frais caché',
    'about.nonexcl3': 'Visibilité sur une marketplace dédiée',
    'about.nonexcl4': 'Communauté active et bienveillante',
    // Login
    'login.title': 'Connexion',
    'login.seller_sub': 'Espace dédié aux créateurs et vendeurs de la plateforme.',
    'login.admin_sub': 'Accès réservé aux administrateurs.',
    'login.submitting': 'Connexion…',
    'login.submit': 'Se connecter',
    'login.admin_error': "Compte administrateur, utilisez l'onglet Administrateur.",
    'login.seller_error': "Compte vendeur, utilisez l'onglet Vendeur.",
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.no_account': 'Pas de compte ?',
    'login.forgot': 'Mot de passe oublié ?',
    'login.tab_user': 'Utilisateur',
    'login.tab_seller': 'Vendeur',
    'login.tab_admin': 'Administrateur',
    'login.join_title': 'Rejoignez le serveur Discord GSA',
    'login.join_desc': 'Pour vous connecter ou vous inscrire, vous devez etre membre du serveur Discord officiel GSA.',
    'login.join_error': "Vous n'avez pas encore rejoint le serveur Discord. Cliquez sur Rejoindre le serveur Discord ci-dessous, acceptez l'invitation, puis revenez ici.",
    'login.join_btn': 'Rejoindre le serveur Discord',
    'login.join_retry': 'Je suis membre, me connecter',
    'login.redirecting': 'Redirection...',
    'login.with_discord_seller': 'Se connecter en tant que vendeur avec Discord',
    'login.with_discord': 'Se connecter avec Discord',
    'login.discord_note': 'Vous devez etre membre du serveur Discord GSA pour acceder a la plateforme.',
    'login.access_admin': 'Acceder au panneau',
    'login.not_admin': "Ces identifiants ne sont pas ceux d'un administrateur.",
    'login.error': 'Erreur de connexion',
    'cookie.title': 'Nous respectons votre vie privee',
    'cookie.text': "GSA utilise des cookies pour garantir le fonctionnement de la plateforme (connexion, panier, langue), et uniquement ceux-la. Aucun cookie publicitaire n'est utilise.",
    'cookie.accept': 'Tout accepter',
    'cookie.refuse': 'Tout refuser',
    'cookie.more': 'Voir plus',
    'cookie.manage': 'Gestion des cookies',
    'cookie.manage_sub': 'Activez ou desactivez chaque categorie de cookies.',
    'cookie.back': 'Retour',
    'cookie.essential': 'Cookies essentiels',
    'cookie.essential_desc': 'Indispensables au fonctionnement du site. Toujours actifs.',
    'cookie.always': 'Toujours actifs',
    'cookie.active': 'Actif',
    'cookie.prefs': 'Cookies de preferences',
    'cookie.prefs_desc': 'Memorisent vos choix pour ameliorer votre experience.',
    'cookie.analytics': "Cookies d'analyse",
    'cookie.analytics_desc': "Aucun cookie de ce type n'est utilise actuellement.",
    'cookie.none': 'Aucun',
    'cookie.save': 'Enregistrer mes choix',
    'cookie.desc_session': 'Session de connexion (authentification)',
    'cookie.desc_cart': "Panier d'achat",
    'cookie.desc_locale': 'Langue preferee',
    'cookie.desc_consent': 'Memorisation de votre choix de cookies',
    'cookie.desc_return': 'Retour apres paiement (confirmation de session)',
    'wa.title': 'Livraison immediate - renonciation au droit de retractation',
    'wa.desc1': "Vous etes sur le point d'acheter un <strong>contenu numerique telecharge immediatement</strong> apres le paiement.",
    'wa.desc2': "Conformement a l'article <strong>L221-28 du Code de la consommation</strong>, en acceptant la livraison immediate du contenu, vous <strong>renoncez expressement a votre droit de retractation</strong>. Aucun remboursement ne sera possible apres le telechargement, sauf produit non conforme.",
    'wa.ack': 'Je comprends que la livraison est immediate et je renonce a mon droit de retractation.',
    'wa.cancel': 'Annuler',
    'wa.confirm': 'Continuer vers le paiement',
    'cart.delete_title': 'Supprimer cet article ?',
    'cart.cancel': 'Annuler',
    'cart.delete': 'Supprimer',

    // Register
    'register.title': 'Créer un compte',
    'register.buyer': 'Acheteur',
    'register.buyer_sub': 'Accéder à la marketplace',
    'register.seller': 'Vendeur',
    'register.seller_sub': 'Vendre vos créations',
    'register.discord_linked': 'Compte Discord lié',
    'register.username': "Nom d'utilisateur",
    'register.email': 'Email',
    'register.password': 'Mot de passe',
    'register.intro': 'Présentez-vous',
    'register.intro_ph': 'Je suis développeur Lua depuis 5 ans…',
    'register.create_buyer': 'Créer mon compte',
    'register.create_seller': 'Créer mon compte vendeur',
    'register.success': 'Compte créé !',
    'register.has_account': 'Déjà un compte ?',
    'register.login_link': 'Se connecter',
    'register.join_desc': 'Pour vous inscrire, vous devez etre membre du serveur Discord officiel GSA.',
    'register.join_retry': "Je suis membre, m'inscrire",
    'register.verify_title': 'Verifiez votre email',
    'register.verify_sub': 'Un code de validation a ete envoye a <strong>{email}</strong>.',
    'register.devcode': 'Mode demo (email non configure) - votre code :',
    'register.verify_code': 'Code de validation',
    'register.verifying': 'Verification...',
    'register.verify_btn': 'Valider mon email',
    'register.with_discord_seller': "S'inscrire en tant que vendeur avec Discord",
    'register.with_discord': "S'inscrire avec Discord",
    'register.terms_title_seller': 'Contrat vendeur',
    'register.terms_title': 'Conditions generales',
    'register.terms_scroll': "Scrollez jusqu'en bas pour accepter les conditions.",
    'register.terms_docs': 'Documents a accepter ({n}) :',
    'register.terms_accept': "J'ai lu et j'accepte l'ensemble des documents ci-dessus.",
    'register.terms_confirm': 'Confirmer et continuer',
    'register.terms_preamble': 'Preambule',
    'register.terms_preamble_p1': "GSA est une plateforme numerique specialisee dans la distribution, la valorisation et la commercialisation de ressources numeriques destinees a la creation de projets videoludiques. GSA exerce une activite hybride comprenant une activite de marketplace mettant en relation vendeurs et acheteurs, une activite de prestation de services lies a la presentation, la selection et la promotion des contenus, et une activite de creation et de fourniture de prestations professionnelles realisees directement par GSA.",
    'register.terms_preamble_p2': "Le present contrat regit les relations entre <strong>GSA Store</strong> (ci-apres GSA ou la Plateforme) et tout createur inscrit en qualite de vendeur (ci-apres le Vendeur). En creant un compte vendeur, le Vendeur accepte sans reserve l'integralite des presentes conditions ainsi que les Fondations Juridiques de GSA.",
    'register.terms_art1': 'Article 1 - Definitions',
    'register.terms_art1_p1': "Les termes utilisés dans le présent contrat s'entendent au sens des Fondations Juridiques de GSA (version 1.0.0) :",
    'register.terms_art1_l1': '<strong>Produit numerique</strong> : tout contenu immateriel propose a la vente (modeles 3D, textures, environnements, maps, effets visuels, interfaces, sons, animations, ressources pour moteurs de jeux...) ;',
    'register.terms_art1_l2': '<strong>Validation GSA</strong> : processus interne de controle humain effectue avant publication - prestation de controle qualite, ne constituant ni certification technique absolue, ni garantie contre tout defaut, ni garantie de compatibilite ;',
    'register.terms_art1_l3': "<strong>Presentation GSA</strong> : miniatures, captures, videos, descriptions et textes promotionnels prepares par GSA, proteges au titre du droit d'auteur ;",
    'register.terms_art1_l4': '<strong>Commission</strong> : remuneration percue par GSA, definie contractuellement avec chaque Vendeur.',
    'register.terms_art2': 'Article 2 - Nature du role de GSA',
    'register.terms_art2_p1': "GSA agit en qualite d'operateur de plateforme permettant la mise en relation entre vendeurs et acheteurs. Sauf indication contraire, GSA n'est ni l'auteur des contenus proposes par les Vendeurs, ni le titulaire des droits attaches a ces contenus, ni le developpeur des produits commercialises par des tiers. Les obligations relatives au contenu vendu demeurent a la charge du Vendeur concerne.",
    'register.terms_art3': 'Article 3 - Obligations du Vendeur',
    'register.terms_art3_p1': 'Le Vendeur demeure responsable :',
    'register.terms_art3_l1': "de la titularite des droits attaches aux contenus proposes (contenu original ou realise avec l'autorisation expresse des ayants droit) ;",
    'register.terms_art3_l2': 'de la conformite juridique des produits et du respect des licences tierces applicables ;',
    'register.terms_art3_l3': "de l'exactitude des informations fournies (descriptions, images, documentation) ;",
    'register.terms_art3_l4': 'de ne pas publier de contenu contraire aux lois, aux droits des tiers ou aux bonnes moeurs.',
    'register.terms_art4': 'Article 4 - Commission et paiements',
    'register.terms_art4_p1': "La Plateforme preleve une commission de <strong>25%</strong> sur le prix de chaque vente (20% pour les vendeurs partenaires), qui remunere notamment l'acces a la plateforme, la visibilite, la Validation GSA, la Presentation GSA, la gestion technique et le support de premier niveau. Les paiements sont traites exclusivement via Stripe : le Vendeur doit disposer d'un compte Stripe Connect actif pour recevoir ses fonds. Le montant net, apres deduction de la commission, est transfere dans les delais prevus par Stripe (generalement 2 a 7 jours ouvrés). Les frais de traitement Stripe (1,5% + 0,25 EUR par transaction) restent a la charge de la Plateforme.",
    'register.terms_art5': 'Article 5 - Propriete intellectuelle et licence de vente',
    'register.terms_art5_p1': "Le Vendeur conserve l'integralite des droits de propriete intellectuelle sur ses creations. Il concede a GSA une licence non exclusive lui permettant de representer, stocker et distribuer les creations dans le cadre strict de la vente. L'acheteur acquiert une Licence GSA : non exclusive, personnelle, non transferable, sans transfert de propriete et sans droit de redistribution. Sont notamment interdits sauf autorisation : la reproduction, la redistribution, la revente, la mise a disposition publique et l'exploitation commerciale non autorisee des contenus.",
    'register.terms_art6': 'Article 6 - Hierarchie contractuelle',
    'register.terms_art6_p1': "Les documents contractuels applicables sont : 1. Mentions legales ; 2. Conditions Generales d'Utilisation ; 3. Conditions Generales de Vente ; 4. Licence GSA ; 5. Contrat vendeur (present contrat) ; 6. Politiques complementaires. En cas de contradiction, le document specifique prevaut sur le document general. En cas de manquement grave aux presentes conditions, GSA se reserve le droit de suspendre ou supprimer le compte Vendeur. Le droit applicable est le droit francais.",
    'register.terms_cgv_title': '1. Conditions generales de vente (CGV)',
    'register.terms_cgv_p1': "Les presentes CGV regissent les achats effectues sur la Plateforme GSA Store. Toute commande implique l'acceptation des presentes conditions. Les prix sont affiches en euros, TTC. La Plateforme se reserve le droit de modifier ses prix a tout moment, les produits etant factures sur la base du tarif en vigueur au moment de la commande.",
    'register.terms_cgu_title': "2. Conditions generales d'utilisation (CGU)",
    'register.terms_cgu_p1': 'En utilisant la Plateforme, vous vous engagez a :',
    'register.terms_cgu_l1': 'Fournir des informations exactes lors de la creation de votre compte ;',
    'register.terms_cgu_l2': 'Ne pas porter atteinte aux droits des createurs (pas de redistribution, copie ou revente des creations telechargees) ;',
    'register.terms_cgu_l3': 'Ne pas publier de contenu illegal, frauduleux ou malveillant ;',
    'register.terms_cgu_l4': 'Ne pas contourner les systemes de paiement ou de protection de la Plateforme.',
    'register.terms_pay_title': '3. Paiement et livraison',
    'register.terms_pay_p1': "Les paiements sont securises et traites via Stripe. Apres validation du paiement, l'acces au telechargement de la creation est immediat dans votre espace Mes telechargements. En cas de paiement effectue mais non confirme, une verification automatique est effectuee et le produit est debloque des confirmation.",
    'register.terms_with_title': '4. Droit de retractation et remboursements',
    'register.terms_with_p1': "Conformement a l'article L221-28 du Code de la consommation, le droit de retractation ne s'applique pas aux contenus numeriques fournis immediatement et telecharges. Toutefois, en cas de produit non conforme ou non fonctionnel, le remboursement peut etre accorde sous 14 jours apres etude de la demande. Contactez le support via le vendeur ou la Plateforme.",
    'register.terms_ip_title': '5. Propriete intellectuelle',
    'register.terms_ip_p1': "Les creations restent la propriete de leurs auteurs. L'achat confere une licence d'utilisation personnelle, non transferable et non exclusive. Toute redistribution, revente ou copie du contenu telecharge est interdite.",
    'register.terms_data_title': '6. Protection des donnees',
    'register.terms_data_p1': 'Vos donnees personnelles sont traitees conformement au RGPD. Elles sont utilisees pour la gestion de votre compte, des commandes et de la relation client, et ne sont jamais revendues a des tiers.',
    'register.terms_liab_title': '7. Responsabilite et litiges',
    'register.terms_liab_p1': 'La Plateforme agit comme intermediaire technique entre vendeurs et acheteurs. En cas de litige, une solution amiable sera recherchee en priorite. Le droit applicable est le droit francais.',

    'register.cgv_accept': "J'accepte les conditions générales de vente",
    // Product
    'product.one_time': 'Paiement unique, accès à vie',
    'product.add_cart': 'Ajouter au panier',
    'product.buy_now': 'Acheter maintenant',
    'product.buy_now_label': 'Achat rapide',
    'product.in_cart': 'Dans le panier',
    'product.added_cart': 'Ajouté au panier',
    'product.owned': 'Déjà obtenu',
    'product.download': 'Télécharger',
    'product.already_cart': 'Déjà dans le panier',
    'product.support_6m': 'Support 6 mois',
    'product.verified': 'Vendeur vérifié',
    'product.features': 'Caractéristiques',
    'product.secure_payment': 'Paiement sécurisé',
    'product.instant_access': 'Accès immédiat',
    'product.gsa_protected': 'Protégé par GSA',
    'product.stripe_secure': 'Paiement sécurisé via Stripe',
    'product.lifetime_access': 'Accès à vie',
    'product.downloadable_updated': 'Téléchargeable et mis à jour',
    'product.documentation': 'Documentation',
    'product.install_guide': "Guide d'installation inclus",
    'product.support_incl': 'Support inclus',
    'product.support_desc': 'Assistance pendant 6 mois',
    'product.verified_item': 'Produit vérifié',
    'product.verified_desc': 'Testé et validé par notre équipe',
    'product.reviews': 'Avis',
    'product.reviews_empty': 'Aucun avis pour le moment.',
    'product.reviews_verified': 'Achat vérifié',
    'product.reviews_yours': 'Votre avis',
    'product.reviews_login': 'Connectez-vous pour laisser un avis.',
    'product.reviews_need_purchase': 'Achetez ce produit pour laisser un avis.',
    'product.reviews_write': 'Laissez un avis',
    'product.reviews_update_title': 'Modifiez votre avis',
    'product.reviews_placeholder': 'Partagez votre expérience avec ce produit...',
    'product.reviews_submit': 'Publier mon avis',
    'product.reviews_update': 'Mettre à jour mon avis',
    'product.reviews_delete': 'Supprimer',
    'product.reviews_delete_confirm_title': 'Supprimer mon avis',
    'product.reviews_delete_confirm': 'Voulez-vous vraiment supprimer votre avis ?',
    'product.reviews_submitted': 'Merci pour votre avis !',
    'product.reviews_updated': 'Avis mis à jour',
    'product.reviews_deleted': 'Avis supprimé',
    'product.reviews_error': 'Erreur lors de l\'envoi de l\'avis',
    // Cart
    'cart.title': 'Panier',
    'cart.secure': 'Paiement sécurisé · Livraison instantanée',
    'cart.empty': 'Votre panier est vide.',
    'cart.empty_sub': 'Découvrez nos produits et trouvez ce quil vous faut.',
    'cart.explore': 'Explorer la marketplace',
    'cart.summary': 'Récapitulatif',
    'cart.discount': 'Réduction',
    'cart.total': 'Total',
    'cart.checkout': 'Passer la commande',
    'cart.step1': 'Panier',
    'cart.step2': 'Paiement',
    'cart.step3': 'Terminé',
    'cart.success': 'Paiement réussi !',
    'cart.success_msg': 'Votre commande a été confirmée. Vous pouvez dès maintenant télécharger vos produits.',
    'cart.my_downloads': 'Mes téléchargements',
    'cart.pending': 'Votre paiement a bien été reçu, mais la confirmation prend quelques instants.',
    'cart.retry': 'Réessayer',
    'cart.see_downloads': 'Voir mes téléchargements',
    'cart.promo_placeholder': 'Code promo',
    'cart.promo_apply': 'Appliquer',
    'cart.promo_applied': 'Code appliqué !',
    'cart.promo_invalid': 'Code invalide ou expiré',
    'cart.remove': 'Retirer',
    // Downloads
    'downloads.loading': 'Chargement…',
    'downloads.title': 'Mes téléchargements',
    'downloads.subtitle': 'Retrouvez tous vos achats et téléchargez vos fichiers.',
    'downloads.none': 'Aucun téléchargement',
    'downloads.none_sub': "Vous n'avez encore rien acheté sur la marketplace.",
    'downloads.downloading': 'Téléchargement…',
    'downloads.download': 'Télécharger',
    'downloads.purchased': 'Acheté le',
    'downloads.retry': 'Réessayer',
    'downloads.auth_error': 'Vous devez être connecté pour voir vos achats.',
    'downloads.net_error': 'Erreur réseau, vérifiez votre connexion.',
    'downloads.srv_error': 'Erreur serveur, réessayez plus tard.',
    'downloads.dl_started': 'Téléchargement démarré ✓',
    'downloads.dl_error': 'Erreur de téléchargement',
    'downloads.pay_confirmed': 'Paiement confirmé !',
    'downloads.confirm_hint': 'Cliquez sur "Vérifier" pour confirmer le paiement',
    'downloads.order_confirmed': 'Commande confirmée !',
    'downloads.confirm_error': 'Erreur lors de la confirmation. Rafraîchissez la page.',
    'downloads.manual_title': 'Vous avez payé mais rien ne s\'affiche ?',
    'downloads.manual_sub': "Collez l'ID de session Stripe ici :",
    'downloads.processing': 'Confirmation en cours…',
    'downloads.pay_received': 'Paiement reçu !',
    'downloads.verify': 'Vérifier',
    'downloads.force_confirm': 'Forcer la confirmation',
    'downloads.invoice': 'Facture',
    'downloads.invoice_sub': 'Télécharger la facture de cette commande',
    'downloads.invoice_pdf': 'Facture (PDF)',
    'downloads.invoice_gen': 'Génération de votre facture…',
    'downloads.invoice_gen_sub': 'Préparation de votre document PDF sécurisé. Cela ne prend que quelques secondes.',
    'downloads.no_file': 'Aucun fichier disponible pour ce produit.',
    'downloads.review_modal_title': 'Merci pour votre achat !',
    'downloads.review_modal_sub': 'Votre avis aide la communauté. Notez votre produit :',
    'downloads.review_modal_btn': 'Laisser un avis',
    'downloads.review_modal_later': 'Plus tard',
    // Prestation
    'prestation.title': 'Prestation',
    'prestation.consulting': 'Consulting & accompagnement',
    'prestation.consulting_desc': "De l'idée à la réalisation, je vous accompagne dans la conception et le développement de votre projet Garry's Mod.",
    'prestation.game_design': 'Game Design',
    'prestation.game_design_desc': 'Conception de mécaniques de jeu, équilibrage et optimisation pour garantir une expérience de qualité à vos joueurs.',
    'prestation.matchmaking': 'Mise en relation',
    'prestation.matchmaking_desc': "Vous avez besoin d'un développeur, d'un designer ou d'un asset spécifique ? Je vous mets en relation avec le bon prestataire.",
    'prestation.need_analysis': 'Analyse des besoins',
    'prestation.architecture': 'Architecture technique',
    'prestation.followup': 'Suivi et itérations',
    'prestation.documentation': 'Documentation complète',
    'prestation.mechanics': 'Mécaniques de jeu',
    'prestation.balance': 'Équilibrage économique',
    'prestation.progression': 'Progression et levelling',
    'prestation.testing': 'Tests et feedback',
    'prestation.devs': 'Développeurs qualifiés',
    'prestation.designers': 'Designers talentueux',
    'prestation.assets': 'Assets sur mesure',
    'prestation.guarantee': 'Garantie de qualité',
    // Seller account
    'seller.title': 'Espace vendeur',
    'seller.subtitle': 'Gérez votre profil et vos moyens de paiement.',
    'seller.profile': 'Profil',
    'seller.bio': 'Bio',
    'seller.bio_ph': 'Présentez votre travail…',
    'seller.save': 'Enregistrer',
    'seller.saved': 'Profil mis à jour !',
    'seller.linked': 'Comptes liés',
    'seller.discord_linked': 'Lié ✓',
    'seller.steam_linked': 'Lié ✓',
    'seller.stripe': 'Paiements',
    'seller.stripe_linked': 'Compte Stripe lié',
    'seller.stripe_unlinked': 'Stripe non connecté',
    'seller.stripe_unlinked_hint': 'Connectez Stripe pour recevoir vos paiements.',
    'seller.stripe_checking': 'Vérification du compte Stripe…',
    'seller.stripe_ok': 'Compte Stripe connecté ✓',
    'seller.stripe_dashboard': 'Dashboard Stripe',
    'seller.connect_stripe': 'Lier le compte Stripe',
    'seller.stripe_timeout': 'La vérification a pris trop de temps. Cliquez sur le bouton pour relier votre compte Stripe.',
    'seller.account_tab': 'Mon compte',
    'seller.revenue_tab': 'Revenus',
    'seller.stripe_incomplete': 'Onboarding Stripe incomplet',
    'seller.resume_onboarding': "Reprendre l'onboarding",
    'seller.stripe_onboarding_hint': 'Votre compte Stripe existe mais l\'onboarding n\'est pas terminé. Reprenez-le pour recevoir vos paiements.',
    'seller.bio_default': "Créateur de contenu pour Garry's Mod.",
    'seller.discord': 'Discord',
    'seller.steam': 'Steam',
    'seller.connected': 'Connecté',
    'seller.not_connected': 'Non connecté',
    'seller.link': 'Lier',
    'seller.copy_id': "Copier l'ID",
    'seller.copied': 'Copié !',
    'seller.discord_desc': 'Recevez vos commandes et restez connecté à votre communauté.',
    'seller.steam_desc': "Prouvez votre identité de joueur Garry's Mod.",
    // Seller page
    'seller.verified': 'Vérifié',
    'seller.verified_by': 'Vérifié par GSA',
    'seller.products': 'Produits',
    'seller.no_products': 'Aucun produit pour le moment.',
    'seller.about': 'À propos',
    'seller.member_since': 'Membre depuis',
    'seller.discord_id_copied': 'Discord ID copié !',
    'seller.link_copied': 'Lien copié !',
    'seller.no_bio': 'Pas de description.',
    // Generic
    'generic.loading': 'Chargement…',
    'generic.error': 'Erreur',
    'generic.cancel': 'Annuler',
    'generic.save': 'Enregistrer',
    'generic.close': 'Fermer',
    'generic.back': 'Retour',
    'generic.copied': 'Copié !',
    'catalogue.all': 'Tout',
    'catalogue.sort_by': 'Trier par',
    'catalogue.platform': 'Plateforme',
    'catalogue.max_price': 'Prix max.',
    'catalogue.options': 'Options',
    'catalogue.min_rating': 'Note minimale',
    'catalogue.reset': 'Réinitialiser',
    'catalogue.sort_popular': 'Les plus populaires',
    'catalogue.sort_newest': 'Plus récents',
    'catalogue.sort_price_asc': 'Prix croissant',
    'catalogue.sort_price_desc': 'Prix décroissant',
    'catalogue.sort_rating': 'Mieux notés',
    'catalogue.sort_discount': 'Promotions',
    'catalogue.sort_trending': 'Tendances',
    'catalogue.platform_gmod': "Garry's Mod",
    'catalogue.platform_ue': 'Unreal Engine',
    'catalogue.no_results': 'Aucun produit ne correspond à vos filtres.',
    'catalogue.results': '{n} produit(s)',
    'prestation.subtitle': 'Game Design & Modélisation 3D',
    'prestation.gd_title': 'Game Design',
    'prestation.gd_desc': "Nous concevons des mécaniques de jeu pensées pour votre projet, quelle que soit sa plateforme. De l'idée initiale à l'équilibrage final, nous transformons vos concepts en expériences cohérentes, engageantes et adaptées à vos joueurs.",
    'prestation.gd_l1': 'Conception de mécaniques sur mesure',
    'prestation.gd_l2': 'Équilibrage et progression',
    'prestation.gd_l3': 'Game Design Document (GDD)',
    'prestation.m3d_title': 'Modélisation 3D architecturale & props',
    'prestation.m3d_desc': "Création de bâtiments, environnements et props sur mesure pour vos projets sous Unreal Engine. Des modèles pensés pour s'intégrer efficacement à votre projet, avec une attention particulière portée aux détails, aux textures et à l'optimisation.",
    'prestation.m3d_l1': 'Bâtiments et structures architecturales',
    'prestation.m3d_l2': 'Environnements et éléments de décor',
    'prestation.m3d_l3': 'Props et objets sur mesure',
    'prestation.discord_cta': 'Pour toute commande ou question, rendez-vous sur le discord',
    'about.hero_h1': 'Pas une boutique. Un standard.',
    'about.hero_intro1': "GSA accompagne les créateurs, développeurs et équipes de production dans la réalisation de leurs projets gaming.",
    'about.hero_intro2': "Nous réunissons ressources numériques, Game Design et création 3D au sein d'une même plateforme, avec une approche simple : proposer des contenus sélectionnés, des services adaptés et un accompagnement humain.",
    'about.label_vision': 'Notre vision',
    'about.vision_h2': 'Créer devrait être plus simple.',
    'about.vision_p1': 'Un projet de jeu ne repose jamais sur une seule compétence.',
    'about.vision_p2': "Il faut concevoir, expérimenter, produire, trouver les bonnes ressources et parfois s'entourer des bonnes personnes. Pourtant, trouver des assets fiables ou obtenir un accompagnement adapté peut rapidement devenir un obstacle supplémentaire.",
    'about.vision_p3': 'GSA est née pour simplifier cette étape.',
    'about.vision_p4': "Notre objectif est de créer un environnement dans lequel les créateurs peuvent trouver ce dont ils ont besoin pour faire avancer leurs projets, sans avoir à passer leur temps à vérifier, comparer et rechercher des ressources.",
    'about.label_market': 'Une marketplace différente',
    'about.market_h2': 'Les contenus ne sont pas simplement mis en ligne.',
    'about.market_p1': 'Sur GSA, un vendeur ne publie pas directement son contenu.',
    'about.market_p2': "Chaque ressource est d'abord soumise à GSA et vérifiée manuellement avant sa publication.",
    'about.market_p3': "Nous examinons le contenu, ses fichiers et les informations nécessaires à sa mise en ligne afin de nous assurer qu'il corresponde aux standards de la plateforme.",
    'about.market_p4': 'Une fois validé, GSA prend également en charge sa présentation.',
    'about.market_p5': "Miniature, captures, vidéo, description et mise en avant : nous préparons le contenu pour qu'il puisse être présenté correctement aux utilisateurs.",
    'about.market_quote1': 'Le vendeur crée.',
    'about.market_quote2': 'GSA sélectionne, prépare et met en avant.',
    'about.label_resources': 'Des ressources pour créer',
    'about.resources_h2': "Tout ce qu'il faut pour donner vie à un projet.",
    'about.resources_p1': 'GSA rassemble progressivement des ressources destinées aux créateurs de jeux et de serveurs.',
    'about.resources_p2': "L'objectif n'est pas de multiplier les contenus pour remplir un catalogue, mais de proposer des ressources réellement pertinentes pour la production : environnements, modèles, props, textures, effets visuels, interfaces, sons et autres éléments permettant de construire une expérience complète.",
    'about.resources_p3': "Chaque contenu est accompagné de conditions d'utilisation clairement définies afin que l'acheteur sache ce qu'il acquiert et dans quelles conditions il peut l'utiliser.",
    'about.label_more': 'Plus que des ressources',
    'about.more_h2': 'Concevoir, produire, améliorer.',
    'about.more_p1': 'Un projet ne se résume pas aux assets qui le composent.',
    'about.more_p2': "GSA propose également des prestations de Game Design pour accompagner les créateurs dans la conception et l'amélioration de leurs projets : réflexion autour des mécaniques, systèmes de gameplay, progression, expérience joueur, documentation ou encore audit de gameplay.",
    'about.more_p3': "Pour compléter cette approche, des prestations de modélisation 3D sont disponibles, permettant de concevoir des environnements, bâtiments, props et autres éléments directement adaptés aux besoins d'un projet.",
    'about.more_p4': 'GSA, un véritable espace de production pour les créateurs.',
    'about.more_cta': 'Découvrir les prestations',
    'about.label_support': 'Un accompagnement humain',
    'about.support_h2': "Parce qu'un achat ne devrait pas s'arrêter au téléchargement.",
    'about.support_p1': 'GSA assure un support de premier niveau après chaque achat.',
    'about.support_p2': "Pendant les sept jours suivant l'achat, notre équipe peut accompagner l'utilisateur lorsqu'il rencontre un problème concernant sa commande ou les fichiers fournis.",
    'about.support_p3': "Lorsqu'un problème concerne directement la conception ou le fonctionnement d'un contenu, GSA peut également intervenir auprès du vendeur afin de faciliter sa résolution.",
    'about.support_p4': 'Notre rôle est simple :',
    'about.support_quote': "Vous permettre de vous concentrer sur votre projet, pas sur les problèmes qui l'entourent.",
    'about.label_licenses': 'Des licences claires',
    'about.licenses_h2': "Vous achetez le droit d'utiliser. Pas la propriété.",
    'about.licenses_p1': "Chaque contenu est accompagné d'une licence définissant les droits accordés à l'acheteur.",
    'about.licenses_p2': "Lorsque le contenu le permet, celui-ci peut notamment être utilisé et modifié dans le cadre de son projet, tout en pouvant être transmis aux intervenants techniques nécessaires à sa réalisation.",
    'about.licenses_p3': 'En revanche, la revente et la redistribution du contenu en tant que ressource indépendante restent interdites.',
    'about.licenses_p4': "Nous voulons que les règles soient compréhensibles avant même l'achat.",
    'about.licenses_quote': 'Pas de zone grise.',
    'about.label_creators': 'Pour les créateurs',
    'about.creators_h2': "Vous créez. GSA s'occupe du reste.",
    'about.creators_p1': "Publier une ressource ne devrait pas obliger un créateur à devenir également graphiste, rédacteur, vidéaste et responsable de sa propre mise en avant.",
    'about.creators_p2': 'GSA prend en charge la préparation du contenu avant sa publication et assure sa présentation sur la plateforme.',
    'about.creators_p3': "Le vendeur conserve ses droits sur sa création et reste responsable de son contenu, tandis que GSA lui fournit un environnement destiné à faciliter sa mise en relation avec des acheteurs.",
    'about.label_objective': 'Notre objectif',
    'about.objective_h2': 'Construire un standard pour les ressources gaming.',
    'about.objective_p1': 'GSA commence avec les ressources destinées aux jeux et aux serveurs.',
    'about.objective_p2': 'Mais notre ambition va plus loin.',
    'about.objective_p3': "Nous voulons construire une plateforme où la qualité des contenus, la clarté des licences et l'accompagnement des utilisateurs deviennent des standards, plutôt que des options.",
    'about.objective_p4': "Un endroit où créateurs, développeurs, artistes et équipes de production peuvent trouver les ressources et les compétences nécessaires pour faire avancer leurs projets.",
    'about.outro_tag': 'Pas une boutique. Un standard.',
    'about.outro_1': 'Des ressources sélectionnées.',
    'about.outro_2': 'Des services pour créer.',
    'about.outro_3': 'Un accompagnement humain.',
    'cart.subtotal': 'Sous-total',
    'cart.browse': 'Parcourir le catalogue',
    'footer.foundations': 'Fondations juridiques',
    'footer.cgu': 'CGU',
    'footer.cookies': 'Politique des cookies',
    'footer.withdrawal': 'Politique de rétractation',
    'footer.contract': 'Contrat vendeur',
    'catalogue.any_rating': 'Toutes',
    'category.3d-model': '3D Model',
    'category.3d-import': '3D Import',
    'category.animation': 'Animation',
    'category.armes': 'Armes',
    'category.map': 'Map',
    'category.particle': 'Particle',
    'category.testmulti': 'TestMulti',
    'category.ui': 'UI',
    'category.voiture': 'Voiture',
    'contact.title': 'Contact',
    'contact.subtitle': 'Une question, une commande, un problème après-achat ? Écrivez-nous.',
    'contact.name': 'Nom *',
    'contact.name_ph': 'Votre nom',
    'contact.email': 'Email *',
    'contact.email_ph': 'vous@exemple.com',
    'contact.subject': 'Sujet',
    'contact.select': 'Sélectionner',
    'contact.sub_question': 'Question sur un produit',
    'contact.sub_order': 'Commande / Téléchargement',
    'contact.sub_after': 'Problème après-achat',
    'contact.sub_seller': 'Devenir vendeur',
    'contact.sub_service': 'Prestation Game Design / 3D',
    'contact.sub_other': 'Autre',
    'contact.message': 'Message *',
    'contact.message_ph': 'Décrivez votre demande...',
    'contact.sending': 'Envoi…',
    'contact.send': 'Envoyer le message',
    'contact.discord_title': 'Discord — réponse rapide',
    'contact.discord_desc': 'Pour une réponse immédiate, rejoignez le serveur communautaire.',
    'contact.email_title': 'Par email',
    'contact.email_desc': "Le formulaire envoie directement votre message à l'équipe GSA.",
    'contact.delay_title': 'Délai de réponse',
    'contact.delay_desc': 'Support de premier niveau sous 7 jours après un achat. Réponse sous 24-48h en moyenne.',
    'product.home': 'Accueil',
    'product.marketplace': 'Marketplace',
    'product.no_description': '<p>Aucune description disponible.</p>',
    'product.no_install': "<p>Aucune instruction d'installation fournie.</p>",
    'product.video_error': 'Lecture intégrée impossible (vidéo non embarquable ou bloquée) —',
  },
  en: {
    'nav.home': 'Home',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.login': 'Sign in',
    'nav.register': 'Sign up',
    'nav.profile': 'My profile',
    'nav.shop': 'My shop',
    'downloads.loading': 'Loading…',
    'nav.downloads': 'My downloads',
    'nav.admin': 'Administration',
    'nav.logout': 'Log out',
    'lang': 'Language',
    'footer.tagline': 'GSA, a standard to come.',
    'footer.platform': 'Platform',
    'footer.legal': 'Legal',
    'footer.cgv': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.legal_notice': 'Legal notice',
    'footer.support': 'Support',
    'footer.discord': 'Discord',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'hero.title1': 'Premium',
    'hero.title2': 'assets,',
    'hero.title3': 'ready to deploy.',
    'hero.desc': 'From mapping to particles — GSA is built by a creator, for creators. Human verification on every product.',
    'hero.explore': 'Explore',
    'hero.assets': 'Assets',
    'hero.sales': 'Sales',
    'hero.rating': 'Rating',
    'hero.creators': 'Creators',
    'hero.themes': 'Themes',
    'hero.themes_sub': 'Dark RP · Medieval · BaseWars · Manga',
    'hero.env': 'Environment',
    'hero.env_sub': 'Ready-to-use Maps & Props',
    'hero.dev': 'Development',
    'hero.dev_sub': 'Tools · Systems · SWEP',
    'hero.visual': 'Visual',
    'hero.visual_sub': '3D models · Particles · Animation · UI',
    'hero.assets_verified': 'verified assets',
    'home.categories': 'Browse by category',
    'home.see_all': 'See all',
    'home.browse_catalog': 'Browse catalog',
    'home.resources': 'resources',
    'home.resource': 'resource',
    'home.trending': 'Trending',
    'home.promotions': 'Promotions',
    'home.collab_tag': 'COLLABORATORS',
    'home.collab_title': 'Collaborators',
    'home.collab_desc': 'Creators who trust us and offer their services.',
    'home.collab_role': 'Collaborator',
    'home.servers_tag': 'PROJECTS',
    'home.servers_title': 'Our clients',
    'home.servers_desc': 'Projects that use and recommend our services.',
    'home.servers_role': 'Project',
    'home.loading': 'Loading…',
    'home.prev': 'Previous',
    'home.next': 'Next',
    'cat.title': 'MARKETPLACE',
    'cat.subtitle': 'EVERYTHING YOU NEED IN ONE PLACE',
    'cat.search': 'Search scripts, models, maps…',
    'cat.all': 'All',
    'cat.filters': 'Filters',
    'cat.sort_by': 'Sort by',
    'cat.popular': 'Most popular',
    'cat.newest': 'Newest',
    'cat.price_asc': 'Price: low to high',
    'cat.price_desc': 'Price: high to low',
    'cat.rating': 'Top rated',
    'cat.discount': 'Promotions',
    'cat.trending': 'Trending',
    'cat.max_price': 'Max price',
    'cat.options': 'Options',
    'cat.on_sale': 'On sale only',
    'cat.verified': 'Verified sellers',
    'cat.trending_only': 'Trending only',
    'cat.min_rating': 'Minimum rating',
    'cat.all_ratings': 'All',
    'cat.reset': 'Reset',
    'cat.apply': 'Apply filters',
    'cat.no_results': 'No results found.',
    'cat.loading': 'Loading…',
    'cat.new': 'NEW',
    'cat.seller': 'Seller',
    'about.title': 'About',
    'about.subtitle': 'GSA, not a shop, a standard.',
    'about.mission_title': 'Our mission',
    'about.mission1': "GSA structures Garry's Mod asset distribution, services and project support in an ecosystem designed for creators.",
    'about.mission2': "Creators spend too much time on the business side at the expense of their art. Project owners struggle to find reliable freelancers. GSA solves both by centralizing distribution, collaboration and funding.",
    'about.list1': 'Showcasing quality assets',
    'about.list2': 'Secure payment handling',
    'about.list3': 'Verified rating and review system',
    'about.list4': 'Creator support',
    'about.list5': 'Dedicated customer support',
    'about.nonexcl_title': 'Why no exclusivity?',
    'about.nonexcl_desc': "We believe creators should be able to sell wherever they want. GSA doesn't impose exclusivity — it's an additional sales channel, no strings attached.",
    'about.nonexcl1': 'Total freedom for creators',
    'about.nonexcl2': 'No hidden fees',
    'about.nonexcl3': 'Visibility on a dedicated marketplace',
    'about.nonexcl4': 'Active and supportive community',
    'login.title': 'Sign in',
    'login.seller_sub': 'Dedicated space for creators and sellers on the platform.',
    'login.admin_sub': 'Restricted access for administrators.',
    'login.submitting': 'Signing in…',
    'login.submit': 'Sign in',
    'login.admin_error': 'Admin account, please use the Admin tab.',
    'login.seller_error': 'Seller account, please use the Seller tab.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.no_account': "Don't have an account?",
    'login.forgot': 'Forgot password?',
    'login.tab_user': 'User',
    'login.tab_seller': 'Seller',
    'login.tab_admin': 'Administrator',
    'login.join_title': 'Join the GSA Discord server',
    'login.join_desc': 'To log in or register, you must be a member of the official GSA Discord server.',
    'login.join_error': 'You have not joined the Discord server yet. Click "Join the Discord server" below, accept the invitation, then come back here.',
    'login.join_btn': 'Join the Discord server',
    'login.join_retry': "I'm a member, log me in",
    'login.redirecting': 'Redirecting...',
    'login.with_discord_seller': 'Sign in as a seller with Discord',
    'login.with_discord': 'Sign in with Discord',
    'login.discord_note': 'You must be a member of the GSA Discord server to access the platform.',
    'login.access_admin': 'Access the admin panel',
    'login.not_admin': 'These credentials are not for an administrator.',
    'login.error': 'Login error',
    'cookie.title': 'We respect your privacy',
    'cookie.text': 'GSA uses cookies to ensure the platform works (login, cart, language), and only those. No advertising cookies are used.',
    'cookie.accept': 'Accept all',
    'cookie.refuse': 'Reject all',
    'cookie.more': 'Learn more',
    'cookie.manage': 'Manage cookies',
    'cookie.manage_sub': 'Enable or disable each cookie category.',
    'cookie.back': 'Back',
    'cookie.essential': 'Essential cookies',
    'cookie.essential_desc': 'Required for the site to work. Always active.',
    'cookie.always': 'Always active',
    'cookie.active': 'Active',
    'cookie.prefs': 'Preference cookies',
    'cookie.prefs_desc': 'Remember your choices to improve your experience.',
    'cookie.analytics': 'Analytics cookies',
    'cookie.analytics_desc': 'No cookies of this type are currently used.',
    'cookie.none': 'None',
    'cookie.save': 'Save my choices',
    'cookie.desc_session': 'Login session (authentication)',
    'cookie.desc_cart': 'Shopping cart',
    'cookie.desc_locale': 'Preferred language',
    'cookie.desc_consent': 'Remembers your cookie choice',
    'cookie.desc_return': 'Return after payment (session confirmation)',
    'wa.title': 'Immediate delivery - waiver of the right of withdrawal',
    'wa.desc1': 'You are about to buy <strong>digital content downloaded immediately</strong> after payment.',
    'wa.desc2': "Under <strong>Article L221-28 of the French Consumer Code</strong>, by accepting immediate delivery of the content, you <strong>expressly waive your right of withdrawal</strong>. No refund is possible after download, except for non-compliant products.",
    'wa.ack': 'I understand that delivery is immediate and I waive my right of withdrawal.',
    'wa.cancel': 'Cancel',
    'wa.confirm': 'Continue to payment',
    'cart.delete_title': 'Remove this item?',
    'cart.cancel': 'Cancel',
    'cart.delete': 'Remove',

    'register.title': 'Create account',
    'register.buyer': 'Buyer',
    'register.buyer_sub': 'Access the marketplace',
    'register.seller': 'Seller',
    'register.seller_sub': 'Sell your creations',
    'register.discord_linked': 'Discord account linked',
    'register.username': 'Username',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.intro': 'Introduce yourself',
    'register.intro_ph': 'I have been a Lua developer for 5 years…',
    'register.create_buyer': 'Create account',
    'register.create_seller': 'Create seller account',
    'register.success': 'Account created!',
    'register.has_account': 'Already have an account?',
    'register.login_link': 'Sign in',
    'register.join_desc': 'To register, you must be a member of the official GSA Discord server.',
    'register.join_retry': "I'm a member, register me",
    'register.verify_title': 'Verify your email',
    'register.verify_sub': 'A validation code was sent to <strong>{email}</strong>.',
    'register.devcode': 'Demo mode (email not configured) - your code:',
    'register.verify_code': 'Validation code',
    'register.verifying': 'Verifying...',
    'register.verify_btn': 'Validate my email',
    'register.with_discord_seller': 'Register as a seller with Discord',
    'register.with_discord': 'Register with Discord',
    'register.terms_title_seller': 'Seller contract',
    'register.terms_title': 'Terms and conditions',
    'register.terms_scroll': 'Scroll to the bottom to accept the terms.',
    'register.terms_docs': 'Documents to accept ({n}):',
    'register.terms_accept': 'I have read and accept all the documents above.',
    'register.terms_confirm': 'Confirm and continue',
    'register.terms_preamble': 'Preamble',
    'register.terms_preamble_p1': 'GSA is a digital platform specialized in the distribution, promotion and sale of digital resources for video game projects. GSA operates a hybrid activity including a marketplace connecting sellers and buyers, a service activity related to content presentation, selection and promotion, and a creation activity providing professional services delivered directly by GSA.',
    'register.terms_preamble_p2': 'This contract governs the relationship between <strong>GSA Store</strong> (hereafter GSA or the Platform) and any creator registered as a seller (hereafter the Seller). By creating a seller account, the Seller unreservedly accepts all of these terms as well as the GSA Legal Foundations.',
    'register.terms_art1': 'Article 1 - Definitions',
    'register.terms_art1_p1': 'The terms used in this contract have the meaning defined in the GSA Legal Foundations (version 1.0.0):',
    'register.terms_art1_l1': '<strong>Digital product</strong>: any intangible content offered for sale (3D models, textures, environments, maps, visual effects, interfaces, sounds, animations, game engine assets...) ;',
    'register.terms_art1_l2': '<strong>GSA Validation</strong>: internal human review process performed before publication - a quality control service, neither an absolute technical certification, nor a warranty against any defect, nor a compatibility guarantee ;',
    'register.terms_art1_l3': '<strong>GSA Presentation</strong>: thumbnails, screenshots, videos, descriptions and promotional texts prepared by GSA, protected by copyright ;',
    'register.terms_art1_l4': '<strong>Commission</strong>: remuneration received by GSA, defined contractually with each Seller.',
    'register.terms_art2': 'Article 2 - Nature of the role of GSA',
    'register.terms_art2_p1': 'GSA operates as a platform operator connecting sellers and buyers. Unless otherwise stated, GSA is neither the author of the content offered by Sellers, nor the owner of the rights attached to that content, nor the developer of products sold by third parties. Obligations relating to the sold content remain the responsibility of the relevant Seller.',
    'register.terms_art3': 'Article 3 - Seller obligations',
    'register.terms_art3_p1': 'The Seller remains responsible for:',
    'register.terms_art3_l1': 'ownership of the rights attached to the offered content (original content or made with the express permission of the rights holders) ;',
    'register.terms_art3_l2': 'legal compliance of the products and compliance with applicable third-party licenses ;',
    'register.terms_art3_l3': 'accuracy of the provided information (descriptions, images, documentation) ;',
    'register.terms_art3_l4': 'not publishing content that violates the law, third-party rights or public decency.',
    'register.terms_art4': 'Article 4 - Commission and payments',
    'register.terms_art4_p1': 'The Platform charges a commission of <strong>25%</strong> on the price of each sale (20% for partner sellers), which covers platform access, visibility, GSA Validation, GSA Presentation, technical management and first-level support. Payments are processed exclusively via Stripe: the Seller must have an active Stripe Connect account to receive funds. The net amount, after commission, is transferred within the timeframes set by Stripe (usually 2 to 7 business days). Stripe processing fees (1.5% + EUR 0.25 per transaction) are borne by the Platform.',
    'register.terms_art5': 'Article 5 - Intellectual property and sales license',
    'register.terms_art5_p1': 'The Seller retains all intellectual property rights on their creations. They grant GSA a non-exclusive license to represent, store and distribute the creations strictly for the purpose of the sale. The buyer acquires a GSA License: non-exclusive, personal, non-transferable, without ownership transfer and without redistribution rights. Unless authorized, the following are prohibited: reproduction, redistribution, resale, public availability and unauthorized commercial exploitation of the content.',
    'register.terms_art6': 'Article 6 - Contractual hierarchy',
    'register.terms_art6_p1': 'The applicable contractual documents are: 1. Legal notices; 2. Terms of Use; 3. Terms of Sale; 4. GSA License; 5. Seller contract (this contract); 6. Additional policies. In case of contradiction, the specific document prevails over the general document. In case of serious breach of these terms, GSA reserves the right to suspend or delete the Seller account. Applicable law is French law.',
    'register.terms_cgv_title': '1. Terms of Sale (CGV)',
    'register.terms_cgv_p1': 'These Terms of Sale govern purchases made on the GSA Store Platform. Any order implies acceptance of these terms. Prices are shown in euros, incl. VAT. The Platform reserves the right to change its prices at any time, products being invoiced at the rate in force at the time of the order.',
    'register.terms_cgu_title': '2. Terms of Use (CGU)',
    'register.terms_cgu_p1': 'By using the Platform, you agree to:',
    'register.terms_cgu_l1': 'Provide accurate information when creating your account ;',
    'register.terms_cgu_l2': 'Not infringe creators rights (no redistribution, copying or resale of downloaded creations) ;',
    'register.terms_cgu_l3': 'Not publish illegal, fraudulent or malicious content ;',
    'register.terms_cgu_l4': 'Not bypass the payment or protection systems of the Platform.',
    'register.terms_pay_title': '3. Payment and delivery',
    'register.terms_pay_p1': 'Payments are secured and processed via Stripe. After payment validation, access to the download of the creation is immediate in your My downloads area. If a payment was made but not confirmed, an automatic check is performed and the product is unlocked upon confirmation.',
    'register.terms_with_title': '4. Right of withdrawal and refunds',
    'register.terms_with_p1': "Under Article L221-28 of the French Consumer Code, the right of withdrawal does not apply to digital content delivered immediately and downloaded. However, in case of a non-compliant or non-functional product, a refund may be granted within 14 days after review of the request. Contact support via the seller or the Platform.",
    'register.terms_ip_title': '5. Intellectual property',
    'register.terms_ip_p1': 'Creations remain the property of their authors. The purchase grants a personal, non-transferable and non-exclusive license. Any redistribution, resale or copy of the downloaded content is prohibited.',
    'register.terms_data_title': '6. Data protection',
    'register.terms_data_p1': 'Your personal data is processed in accordance with the GDPR. It is used for account, order and customer relationship management, and is never sold to third parties.',
    'register.terms_liab_title': '7. Liability and disputes',
    'register.terms_liab_p1': 'The Platform acts as a technical intermediary between sellers and buyers. In case of dispute, an amicable solution will be sought first. Applicable law is French law.',

    'register.cgv_accept': 'I accept the terms and conditions',
    'product.one_time': 'One-time payment, lifetime access',
    'product.buy_now_label': 'Quick buy',
    'product.add_cart': 'Add to cart',
    'product.buy_now': 'Buy now',
    'product.in_cart': 'In cart',
    'product.added_cart': 'Added to cart',
    'product.owned': 'Already owned',
    'product.download': 'Download',
    'product.already_cart': 'Already in cart',
    'product.support_6m': '6-month support',
    'product.verified': 'Verified seller',
    'product.features': 'Features',
    'product.secure_payment': 'Secure payment',
    'product.instant_access': 'Instant access',
    'product.gsa_protected': 'Protected by GSA',
    'product.stripe_secure': 'Secure payment via Stripe',
    'product.lifetime_access': 'Lifetime access',
    'product.downloadable_updated': 'Downloadable & updated',
    'product.documentation': 'Documentation',
    'product.install_guide': 'Installation guide included',
    'product.support_incl': 'Support included',
    'product.support_desc': '6-month assistance',
    'product.verified_item': 'Verified product',
    'product.verified_desc': 'Tested and validated by our team',
    'product.reviews': 'Reviews',
    'product.reviews_empty': 'No reviews yet.',
    'product.reviews_verified': 'Verified purchase',
    'product.reviews_yours': 'Your review',
    'product.reviews_login': 'Log in to leave a review.',
    'product.reviews_need_purchase': 'Purchase this product to leave a review.',
    'product.reviews_write': 'Leave a review',
    'product.reviews_update_title': 'Update your review',
    'product.reviews_placeholder': 'Share your experience with this product...',
    'product.reviews_submit': 'Submit review',
    'product.reviews_update': 'Update my review',
    'product.reviews_delete': 'Delete',
    'product.reviews_delete_confirm_title': 'Delete my review',
    'product.reviews_delete_confirm': 'Are you sure you want to delete your review?',
    'product.reviews_submitted': 'Thanks for your review!',
    'product.reviews_updated': 'Review updated',
    'product.reviews_deleted': 'Review deleted',
    'product.reviews_error': 'Error submitting review',
    'cart.title': 'Cart',
    'cart.secure': 'Secure payment · Instant delivery',
    'cart.empty': 'Your cart is empty.',
    'cart.empty_sub': 'Discover our products and find what you need.',
    'cart.explore': 'Browse marketplace',
    'cart.summary': 'Summary',
    'cart.discount': 'Discount',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.step1': 'Cart',
    'cart.step2': 'Payment',
    'cart.step3': 'Done',
    'cart.success': 'Payment successful!',
    'cart.success_msg': 'Your order has been confirmed. You can now download your products.',
    'cart.my_downloads': 'My downloads',
    'cart.pending': 'Your payment was received, but confirmation is taking a moment.',
    'cart.retry': 'Retry',
    'cart.see_downloads': 'See my downloads',
    'cart.promo_placeholder': 'Promo code',
    'cart.promo_apply': 'Apply',
    'cart.promo_applied': 'Code applied!',
    'cart.promo_invalid': 'Invalid or expired code',
    'cart.remove': 'Remove',
    'downloads.title': 'My downloads',
    'downloads.subtitle': 'Find all your purchases and download your files.',
    'downloads.none': 'No downloads',
    'downloads.none_sub': "You haven't purchased anything on the marketplace yet.",
    'downloads.downloading': 'Downloading…',
    'downloads.download': 'Download',
    'downloads.purchased': 'Purchased on',
    'downloads.retry': 'Retry',
    'downloads.auth_error': 'You must be logged in to see your purchases.',
    'downloads.net_error': 'Network error, check your connection.',
    'downloads.srv_error': 'Server error, try again later.',
    'downloads.dl_started': 'Download started ✓',
    'downloads.dl_error': 'Download error',
    'downloads.pay_confirmed': 'Payment confirmed!',
    'downloads.confirm_hint': 'Click "Verify" to confirm payment',
    'downloads.order_confirmed': 'Order confirmed!',
    'downloads.confirm_error': 'Confirmation error. Refresh the page.',
    'downloads.manual_title': 'You paid but nothing shows up?',
    'downloads.manual_sub': 'Paste your Stripe session ID here:',
    'downloads.processing': 'Confirming…',
    'downloads.pay_received': 'Payment received!',
    'downloads.verify': 'Verify',
    'downloads.force_confirm': 'Force confirmation',
    'downloads.invoice': 'Invoice',
    'downloads.invoice_sub': 'Download the invoice for this order',
    'downloads.invoice_pdf': 'Invoice (PDF)',
    'downloads.invoice_gen': 'Generating your invoice…',
    'downloads.invoice_gen_sub': 'Preparing your secure PDF document. This only takes a few seconds.',
    'downloads.no_file': 'No file available for this product yet.',
    'downloads.review_modal_title': 'Thanks for your purchase!',
    'downloads.review_modal_sub': 'Your review helps the community. Rate your product:',
    'downloads.review_modal_btn': 'Leave a review',
    'downloads.review_modal_later': 'Later',
    'prestation.title': 'Services',
    'prestation.consulting': 'Consulting & support',
    'prestation.consulting_desc': "From idea to completion, I support you in designing and developing your Garry's Mod project.",
    'prestation.game_design': 'Game Design',
    'prestation.game_design_desc': 'Game mechanics design, balancing and optimization to ensure a quality experience for your players.',
    'prestation.matchmaking': 'Matchmaking',
    'prestation.matchmaking_desc': 'Need a developer, designer or a specific asset? I connect you with the right freelancer.',
    'prestation.need_analysis': 'Needs analysis',
    'prestation.architecture': 'Technical architecture',
    'prestation.followup': 'Follow-up & iterations',
    'prestation.documentation': 'Full documentation',
    'prestation.mechanics': 'Game mechanics',
    'prestation.balance': 'Economic balance',
    'prestation.progression': 'Progression & leveling',
    'prestation.testing': 'Testing & feedback',
    'prestation.devs': 'Qualified developers',
    'prestation.designers': 'Talented designers',
    'prestation.assets': 'Custom assets',
    'prestation.guarantee': 'Quality guarantee',
    'seller.title': 'Seller dashboard',
    'seller.subtitle': 'Manage your profile and payment methods.',
    'seller.profile': 'Profile',
    'seller.bio': 'Bio',
    'seller.bio_ph': 'Describe your work…',
    'seller.save': 'Save',
    'seller.saved': 'Profile updated!',
    'seller.linked': 'Linked accounts',
    'seller.discord_linked': 'Linked ✓',
    'seller.steam_linked': 'Linked ✓',
    'seller.stripe': 'Payments',
    'seller.stripe_linked': 'Stripe account linked',
    'seller.stripe_unlinked': 'Stripe not connected',
    'seller.stripe_unlinked_hint': 'Connect Stripe to receive payments.',
    'seller.stripe_checking': 'Checking Stripe account…',
    'seller.stripe_ok': 'Stripe account connected ✓',
    'seller.stripe_dashboard': 'Stripe Dashboard',
    'seller.connect_stripe': 'Link Stripe account',
    'seller.stripe_timeout': 'Verification timed out. Use the button below to link your Stripe account.',
    'seller.account_tab': 'My account',
    'seller.revenue_tab': 'Earnings',
    'seller.stripe_incomplete': 'Stripe onboarding incomplete',
    'seller.resume_onboarding': 'Resume onboarding',
    'seller.stripe_onboarding_hint': 'Your Stripe account exists but onboarding is not complete. Resume it to receive payments.',
    'seller.bio_default': "Garry's Mod content creator.",
    'seller.discord': 'Discord',
    'seller.steam': 'Steam',
    'seller.connected': 'Connected',
    'seller.not_connected': 'Not connected',
    'seller.link': 'Link',
    'seller.copy_id': 'Copy ID',
    'seller.copied': 'Copied!',
    'seller.discord_desc': 'Receive your orders and stay connected to your community.',
    'seller.steam_desc': "Verify your Garry's Mod player identity.",
    'seller.verified': 'Verified',
    'seller.verified_by': 'Verified by GSA',
    'seller.products': 'Products',
    'seller.no_products': 'No products yet.',
    'seller.about': 'About',
    'seller.member_since': 'Member since',
    'seller.discord_id_copied': 'Discord ID copied!',
    'seller.link_copied': 'Link copied!',
    'seller.no_bio': 'No description.',
    'generic.loading': 'Loading…',
    'generic.error': 'Error',
    'generic.cancel': 'Cancel',
    'generic.save': 'Save',
    'generic.close': 'Close',
    'generic.back': 'Back',
    'generic.copied': 'Copied!',
    'catalogue.all': 'All',
    'catalogue.sort_by': 'Sort by',
    'catalogue.platform': 'Platform',
    'catalogue.max_price': 'Max price',
    'catalogue.options': 'Options',
    'catalogue.min_rating': 'Min rating',
    'catalogue.reset': 'Reset',
    'catalogue.sort_popular': 'Most popular',
    'catalogue.sort_newest': 'Newest',
    'catalogue.sort_price_asc': 'Price: low to high',
    'catalogue.sort_price_desc': 'Price: high to low',
    'catalogue.sort_rating': 'Top rated',
    'catalogue.sort_discount': 'Deals',
    'catalogue.sort_trending': 'Trending',
    'catalogue.platform_gmod': "Garry's Mod",
    'catalogue.platform_ue': 'Unreal Engine',
    'catalogue.no_results': 'No products match your filters.',
    'catalogue.results': '{n} product(s)',
    'prestation.subtitle': 'Game Design & 3D Modeling',
    'prestation.gd_title': 'Game Design',
    'prestation.gd_desc': "We design game mechanics tailored to your project, whatever its platform. From the initial idea to the final balancing, we turn your concepts into coherent, engaging experiences adapted to your players.",
    'prestation.gd_l1': 'Custom mechanic design',
    'prestation.gd_l2': 'Balancing and progression',
    'prestation.gd_l3': 'Game Design Document (GDD)',
    'prestation.m3d_title': 'Architectural 3D modeling & props',
    'prestation.m3d_desc': "Creation of custom buildings, environments and props for your Unreal Engine projects. Models designed to integrate efficiently into your project, with particular attention to details, textures and optimization.",
    'prestation.m3d_l1': 'Buildings and architectural structures',
    'prestation.m3d_l2': 'Environments and scenery elements',
    'prestation.m3d_l3': 'Custom props and objects',
    'prestation.discord_cta': 'For any order or question, join the Discord',
    'about.hero_h1': 'Not a shop. A standard.',
    'about.hero_intro1': 'GSA supports creators, developers and production teams in building their gaming projects.',
    'about.hero_intro2': "We bring together digital resources, Game Design and 3D creation on a single platform, with a simple approach: curated content, tailored services and human support.",
    'about.label_vision': 'Our vision',
    'about.vision_h2': 'Creating should be simpler.',
    'about.vision_p1': 'A game project never relies on a single skill.',
    'about.vision_p2': "You have to design, experiment, produce, find the right resources and sometimes surround yourself with the right people. Yet finding reliable assets or getting proper support can quickly become another obstacle.",
    'about.vision_p3': 'GSA was born to simplify this step.',
    'about.vision_p4': "Our goal is to create an environment where creators can find what they need to move their projects forward, without spending their time checking, comparing and hunting for resources.",
    'about.label_market': 'A different marketplace',
    'about.market_h2': 'Content is not simply uploaded.',
    'about.market_p1': 'On GSA, a seller does not publish their content directly.',
    'about.market_p2': 'Each resource is first submitted to GSA and manually verified before publication.',
    'about.market_p3': 'We review the content, its files and the information required to publish it, to make sure it meets the platform standards.',
    'about.market_p4': 'Once validated, GSA also takes care of its presentation.',
    'about.market_p5': "Thumbnail, screenshots, video, description and promotion: we prepare the content so it can be presented properly to users.",
    'about.market_quote1': 'The seller creates.',
    'about.market_quote2': 'GSA selects, prepares and promotes.',
    'about.label_resources': 'Resources to create',
    'about.resources_h2': 'Everything needed to bring a project to life.',
    'about.resources_p1': 'GSA gradually gathers resources intended for game and server creators.',
    'about.resources_p2': "The goal is not to multiply content to fill a catalog, but to offer resources that are truly relevant for production: environments, models, props, textures, visual effects, interfaces, sounds and other elements enabling the building of a complete experience.",
    'about.resources_p3': "Each content comes with clearly defined terms of use, so the buyer knows what they acquire and under which conditions they may use it.",
    'about.label_more': 'More than resources',
    'about.more_h2': 'Design, produce, improve.',
    'about.more_p1': 'A project is not just the assets it is made of.',
    'about.more_p2': "GSA also offers Game Design services to support creators in designing and improving their projects: mechanics thinking, gameplay systems, progression, player experience, documentation or gameplay audit.",
    'about.more_p3': "To complete this approach, 3D modeling services are available, allowing the design of environments, buildings, props and other elements directly tailored to a project's needs.",
    'about.more_p4': 'GSA, a real production space for creators.',
    'about.more_cta': 'Discover our services',
    'about.label_support': 'Human support',
    'about.support_h2': "Because a purchase should not end at the download.",
    'about.support_p1': 'GSA provides first-level support after every purchase.',
    'about.support_p2': "For the seven days following the purchase, our team can assist the user when they encounter a problem with their order or the provided files.",
    'about.support_p3': "When a problem directly concerns the design or functioning of content, GSA may also intervene with the seller to facilitate its resolution.",
    'about.support_p4': 'Our role is simple:',
    'about.support_quote': 'Letting you focus on your project, not on the problems around it.',
    'about.label_licenses': 'Clear licenses',
    'about.licenses_h2': "You buy the right to use. Not the ownership.",
    'about.licenses_p1': "Each content comes with a license defining the rights granted to the buyer.",
    'about.licenses_p2': "Where the content allows it, it may notably be used and modified within one's project, while being shareable with the technical contributors needed for its production.",
    'about.licenses_p3': 'However, reselling and redistributing the content as an independent resource remain prohibited.',
    'about.licenses_p4': 'We want the rules to be understandable before the purchase.',
    'about.licenses_quote': 'No grey area.',
    'about.label_creators': 'For creators',
    'about.creators_h2': "You create. GSA handles the rest.",
    'about.creators_p1': "Publishing a resource should not force a creator to also become a graphic designer, writer, video editor and their own promoter.",
    'about.creators_p2': 'GSA takes care of preparing the content before its publication and ensures its presentation on the platform.',
    'about.creators_p3': "The seller keeps their rights over their creation and remains responsible for their content, while GSA provides an environment designed to make connecting with buyers easier.",
    'about.label_objective': 'Our objective',
    'about.objective_h2': 'Building a standard for gaming resources.',
    'about.objective_p1': 'GSA starts with resources intended for games and servers.',
    'about.objective_p2': 'But our ambition goes further.',
    'about.objective_p3': "We want to build a platform where content quality, license clarity and user support become standards, rather than options.",
    'about.objective_p4': 'A place where creators, developers, artists and production teams can find the resources and skills needed to move their projects forward.',
    'about.outro_tag': 'Not a shop. A standard.',
    'about.outro_1': 'Curated resources.',
    'about.outro_2': 'Services to create.',
    'about.outro_3': 'Human support.',
    'cart.subtotal': 'Subtotal',
    'cart.browse': 'Browse the catalog',
    'footer.foundations': 'Legal foundations',
    'footer.cgu': 'Terms of Use',
    'footer.cookies': 'Cookie policy',
    'footer.withdrawal': 'Withdrawal policy',
    'footer.contract': 'Seller contract',
    'catalogue.any_rating': 'Any',
    'category.3d-model': '3D Model',
    'category.3d-import': '3D Import',
    'category.animation': 'Animation',
    'category.armes': 'Weapons',
    'category.map': 'Map',
    'category.particle': 'Particle',
    'category.testmulti': 'TestMulti',
    'category.ui': 'UI',
    'category.voiture': 'Cars',
    'contact.title': 'Contact',
    'contact.subtitle': 'A question, an order, a post-purchase issue? Write to us.',
    'contact.name': 'Name *',
    'contact.name_ph': 'Your name',
    'contact.email': 'Email *',
    'contact.email_ph': 'you@example.com',
    'contact.subject': 'Subject',
    'contact.select': 'Select',
    'contact.sub_question': 'Question about a product',
    'contact.sub_order': 'Order / Download',
    'contact.sub_after': 'Post-purchase issue',
    'contact.sub_seller': 'Become a seller',
    'contact.sub_service': 'Game Design / 3D service',
    'contact.sub_other': 'Other',
    'contact.message': 'Message *',
    'contact.message_ph': 'Describe your request...',
    'contact.sending': 'Sending…',
    'contact.send': 'Send message',
    'contact.discord_title': 'Discord — quick reply',
    'contact.discord_desc': 'For an immediate answer, join the community server.',
    'contact.email_title': 'By email',
    'contact.email_desc': 'The form sends your message directly to the GSA team.',
    'contact.delay_title': 'Response time',
    'contact.delay_desc': 'First-level support within 7 days after a purchase. Average reply within 24-48h.',
    'product.home': 'Home',
    'product.marketplace': 'Marketplace',
    'product.no_description': '<p>No description available.</p>',
    'product.no_install': '<p>No installation instructions provided.</p>',
    'product.video_error': 'Embedded playback unavailable (video not embeddable or blocked) —',
  },

}

const locale = ref<Locale>('fr')

function initLocale() {
  if (typeof window !== 'undefined') {
    const saved = localStorage.getItem(LOCALE_KEY) as Locale | null
    if (saved && ['fr', 'en'].includes(saved)) {
      locale.value = saved
    }
  }
}

function setLocale(l: Locale) {
  locale.value = l
  localStorage.setItem(LOCALE_KEY, l)
}

function t(key: string, fallback?: string): string {
  return messages[locale.value]?.[key] ?? fallback ?? key
}

export function useLang() {
  return { locale, labels, flagEmoji, initLocale, setLocale, t }
}
