import io

p = "composables/useLang.ts"
s = io.open(p, encoding="utf-8", newline="").read()

fr = """    'about.hero_h1': 'Pas une boutique. Un standard.',
    'about.hero_intro1': "GSA accompagne les créateurs, développeurs et équipes de production dans la réalisation de leurs projets gaming.",
    'about.hero_intro2': "Nous réunissons ressources numériques, Game Design et création 3D au sein d'une même plateforme, avec une approche simple : proposer des contenus sélectionnés, des services adaptés et un accompagnement humain.",
    'about.label_vision': 'Notre vision',
    'about.vision_h2': 'Créer devrait être plus simple.',
    'about.vision_p1': 'Un projet de jeu ne repose jamais sur une seule compétence.',
    'about.vision_p2': "Il faut concevoir, expérimenter, produire, trouver les bonnes ressources et parfois s'entourer des bonnes personnes. Pourtant, trouver des assets fiables ou obtenir un accompagnement adapté peut rapidement devenir un obstacle supplémentaire.",
    'about.vision_p3': 'GSA est née pour simplifier cette étape.',
    'about.vision_p4': "Notre objectif est de créer un environnement dans lequel les créateurs peuvent trouver ce dont ils ont besoin pour faire avancer leurs projets, sans avoir à passer leur temps à vérifier, comparer et rechercher des ressources.",
    'about.label_market': 'Une marketplace différente',
    'about.market_h2': 'Les contenus ne sont pas simplement mis en ligne.',
    'about.market_p1': 'Sur GSA, un vendeur ne publie pas directement son contenu.',
    'about.market_p2': 'Chaque ressource est d'abord soumise à GSA et vérifiée manuellement avant sa publication.',
    'about.market_p3': "Nous examinons le contenu, ses fichiers et les informations nécessaires à sa mise en ligne afin de nous assurer qu'il corresponde aux standards de la plateforme.",
    'about.market_p4': 'Une fois validé, GSA prend également en charge sa présentation.',
    'about.market_p5': "Miniature, captures, vidéo, description et mise en avant : nous préparons le contenu pour qu'il puisse être présenté correctement aux utilisateurs.",
    'about.market_quote1': 'Le vendeur crée.',
    'about.market_quote2': 'GSA sélectionne, prépare et met en avant.',
    'about.label_resources': 'Des ressources pour créer',
    'about.resources_h2': "Tout ce qu'il faut pour donner vie à un projet.",
    'about.resources_p1': 'GSA rassemble progressivement des ressources destinées aux créateurs de jeux et de serveurs.',
    'about.resources_p2': "L'objectif n'est pas de multiplier les contenus pour remplir un catalogue, mais de proposer des ressources réellement pertinentes pour la production : environnements, modèles, props, textures, effets visuels, interfaces, sons et autres éléments permettant de construire une expérience complète.",
    'about.resources_p3': "Chaque contenu est accompagné de conditions d'utilisation clairement définies afin que l'acheteur sache ce qu'il acquiert et dans quelles conditions il peut l'utiliser.",
    'about.label_more': 'Plus que des ressources',
    'about.more_h2': 'Concevoir, produire, améliorer.',
    'about.more_p1': 'Un projet ne se résume pas aux assets qui le composent.',
    'about.more_p2': "GSA propose également des prestations de Game Design pour accompagner les créateurs dans la conception et l'amélioration de leurs projets : réflexion autour des mécaniques, systèmes de gameplay, progression, expérience joueur, documentation ou encore audit de gameplay.",
    'about.more_p3': "Pour compléter cette approche, des prestations de modélisation 3D sont disponibles, permettant de concevoir des environnements, bâtiments, props et autres éléments directement adaptés aux besoins d'un projet.",
    'about.more_p4': 'GSA, un véritable espace de production pour les créateurs.',
    'about.more_cta': 'Découvrir les prestations',
    'about.label_support': 'Un accompagnement humain',
    'about.support_h2': "Parce qu'un achat ne devrait pas s'arrêter au téléchargement.",
    'about.support_p1': 'GSA assure un support de premier niveau après chaque achat.',
    'about.support_p2': "Pendant les sept jours suivant l'achat, notre équipe peut accompagner l'utilisateur lorsqu'il rencontre un problème concernant sa commande ou les fichiers fournis.",
    'about.support_p3': "Lorsqu'un problème concerne directement la conception ou le fonctionnement d'un contenu, GSA peut également intervenir auprès du vendeur afin de faciliter sa résolution.",
    'about.support_p4': 'Notre rôle est simple :',
    'about.support_quote': 'Vous permettre de vous concentrer sur votre projet, pas sur les problèmes qui l'entourent.',
    'about.label_licenses': 'Des licences claires',
    'about.licenses_h2': "Vous achetez le droit d'utiliser. Pas la propriété.",
    'about.licenses_p1': "Chaque contenu est accompagné d'une licence définissant les droits accordés à l'acheteur.",
    'about.licenses_p2': "Lorsque le contenu le permet, celui-ci peut notamment être utilisé et modifié dans le cadre de son projet, tout en pouvant être transmis aux intervenants techniques nécessaires à sa réalisation.",
    'about.licenses_p3': 'En revanche, la revente et la redistribution du contenu en tant que ressource indépendante restent interdites.',
    'about.licenses_p4': "Nous voulons que les règles soient compréhensibles avant même l'achat.",
    'about.licenses_quote': 'Pas de zone grise.',
    'about.label_creators': 'Pour les créateurs',
    'about.creators_h2': "Vous créez. GSA s'occupe du reste.",
    'about.creators_p1': "Publier une ressource ne devrait pas obliger un créateur à devenir également graphiste, rédacteur, vidéaste et responsable de sa propre mise en avant.",
    'about.creators_p2': 'GSA prend en charge la préparation du contenu avant sa publication et assure sa présentation sur la plateforme.',
    'about.creators_p3': "Le vendeur conserve ses droits sur sa création et reste responsable de son contenu, tandis que GSA lui fournit un environnement destiné à faciliter sa mise en relation avec des acheteurs.",
    'about.label_objective': 'Notre objectif',
    'about.objective_h2': 'Construire un standard pour les ressources gaming.',
    'about.objective_p1': 'GSA commence avec les ressources destinées aux jeux et aux serveurs.',
    'about.objective_p2': 'Mais notre ambition va plus loin.',
    'about.objective_p3': "Nous voulons construire une plateforme où la qualité des contenus, la clarté des licences et l'accompagnement des utilisateurs deviennent des standards, plutôt que des options.",
    'about.objective_p4': "Un endroit où créateurs, développeurs, artistes et équipes de production peuvent trouver les ressources et les compétences nécessaires pour faire avancer leurs projets.",
    'about.outro_tag': 'Pas une boutique. Un standard.',
    'about.outro_1': 'Des ressources sélectionnées.',
    'about.outro_2': 'Des services pour créer.',
    'about.outro_3': 'Un accompagnement humain.',
"""
en = """    'about.hero_h1': 'Not a shop. A standard.',
    'about.hero_intro1': 'GSA supports creators, developers and production teams in building their gaming projects.',
    'about.hero_intro2': "We bring together digital resources, Game Design and 3D creation on a single platform, with a simple approach: curated content, tailored services and human support.",
    'about.label_vision': 'Our vision',
    'about.vision_h2': 'Creating should be simpler.',
    'about.vision_p1': 'A game project never relies on a single skill.',
    'about.vision_p2': "You have to design, experiment, produce, find the right resources and sometimes surround yourself with the right people. Yet finding reliable assets or getting proper support can quickly become another obstacle.",
    'about.vision_p3': 'GSA was born to simplify this step.',
    'about.vision_p4': "Our goal is to create an environment where creators can find what they need to move their projects forward, without spending their time checking, comparing and hunting for resources.",
    'about.label_market': 'A different marketplace',
    'about.market_h2': 'Content is not simply uploaded.',
    'about.market_p1': 'On GSA, a seller does not publish their content directly.',
    'about.market_p2': 'Each resource is first submitted to GSA and manually verified before publication.',
    'about.market_p3': 'We review the content, its files and the information required to publish it, to make sure it meets the platform standards.',
    'about.market_p4': 'Once validated, GSA also takes care of its presentation.',
    'about.market_p5': "Thumbnail, screenshots, video, description and promotion: we prepare the content so it can be presented properly to users.",
    'about.market_quote1': 'The seller creates.',
    'about.market_quote2': 'GSA selects, prepares and promotes.',
    'about.label_resources': 'Resources to create',
    'about.resources_h2': 'Everything needed to bring a project to life.',
    'about.resources_p1': 'GSA gradually gathers resources intended for game and server creators.',
    'about.resources_p2': "The goal is not to multiply content to fill a catalog, but to offer resources that are truly relevant for production: environments, models, props, textures, visual effects, interfaces, sounds and other elements enabling the building of a complete experience.",
    'about.resources_p3': "Each content comes with clearly defined terms of use, so the buyer knows what they acquire and under which conditions they may use it.",
    'about.label_more': 'More than resources',
    'about.more_h2': 'Design, produce, improve.',
    'about.more_p1': 'A project is not just the assets it is made of.',
    'about.more_p2': "GSA also offers Game Design services to support creators in designing and improving their projects: mechanics thinking, gameplay systems, progression, player experience, documentation or gameplay audit.",
    'about.more_p3': "To complete this approach, 3D modeling services are available, allowing the design of environments, buildings, props and other elements directly tailored to a project's needs.",
    'about.more_p4': 'GSA, a real production space for creators.',
    'about.more_cta': 'Discover our services',
    'about.label_support': 'Human support',
    'about.support_h2': "Because a purchase should not end at the download.",
    'about.support_p1': 'GSA provides first-level support after every purchase.',
    'about.support_p2': "For the seven days following the purchase, our team can assist the user when they encounter a problem with their order or the provided files.",
    'about.support_p3': "When a problem directly concerns the design or functioning of content, GSA may also intervene with the seller to facilitate its resolution.",
    'about.support_p4': 'Our role is simple:',
    'about.support_quote': 'Letting you focus on your project, not on the problems around it.',
    'about.label_licenses': 'Clear licenses',
    'about.licenses_h2': "You buy the right to use. Not the ownership.",
    'about.licenses_p1': "Each content comes with a license defining the rights granted to the buyer.",
    'about.licenses_p2': "Where the content allows it, it may notably be used and modified within one's project, while being shareable with the technical contributors needed for its production.",
    'about.licenses_p3': 'However, reselling and redistributing the content as an independent resource remain prohibited.',
    'about.licenses_p4': 'We want the rules to be understandable before the purchase.',
    'about.licenses_quote': 'No grey area.',
    'about.label_creators': 'For creators',
    'about.creators_h2': "You create. GSA handles the rest.",
    'about.creators_p1': "Publishing a resource should not force a creator to also become a graphic designer, writer, video editor and their own promoter.",
    'about.creators_p2': 'GSA takes care of preparing the content before its publication and ensures its presentation on the platform.',
    'about.creators_p3': "The seller keeps their rights over their creation and remains responsible for their content, while GSA provides an environment designed to make connecting with buyers easier.",
    'about.label_objective': 'Our objective',
    'about.objective_h2': 'Building a standard for gaming resources.',
    'about.objective_p1': 'GSA starts with resources intended for games and servers.',
    'about.objective_p2': 'But our ambition goes further.',
    'about.objective_p3': "We want to build a platform where content quality, license clarity and user support become standards, rather than options.",
    'about.objective_p4': 'A place where creators, developers, artists and production teams can find the resources and skills needed to move their projects forward.',
    'about.outro_tag': 'Not a shop. A standard.',
    'about.outro_1': 'Curated resources.',
    'about.outro_2': 'Services to create.',
    'about.outro_3': 'Human support.',
"""

def insert_after_last(s, anchor_start, block):
    idx = s.find(anchor_start)
    end = s.find("\n  },", idx)
    return s[:end] + "\n" + block + s[end:]

s = insert_after_last(s, "  fr: {", fr.rstrip())
s = insert_after_last(s, "  en: {", en.rstrip())
io.open(p, "w", encoding="utf-8", newline="").write(s)
print("cles about ajoutees")
