import io, re

# ============ 1) AJOUT DES CLES fr/en DANS useLang.ts ============
p = "composables/useLang.ts"
s = io.open(p, encoding="utf-8", newline="").read()

fr = """    'register.seller': 'Vendeur',
    'register.join_desc': 'Pour vous inscrire, vous devez etre membre du serveur Discord officiel GSA.',
    'register.join_retry': "Je suis membre, m'inscrire",
    'register.verify_title': 'Verifiez votre email',
    'register.verify_sub': 'Un code de validation a ete envoye a <strong>{email}</strong>.',
    'register.devcode': 'Mode demo (email non configure) - votre code :',
    'register.verify_code': 'Code de validation',
    'register.verifying': 'Verification...',
    'register.verify_btn': 'Valider mon email',
    'register.with_discord_seller': "S'inscrire en tant que vendeur avec Discord",
    'register.with_discord': "S'inscrire avec Discord",
    'register.terms_title_seller': 'Contrat vendeur',
    'register.terms_title': 'Conditions generales',
    'register.terms_scroll': 'Scrollez jusqu'en bas pour accepter les conditions.',
    'register.terms_docs': 'Documents a accepter ({n}) :',
    'register.terms_accept': "J'ai lu et j'accepte l'ensemble des documents ci-dessus.",
    'register.terms_confirm': 'Confirmer et continuer',
    'register.terms_preamble': 'Preambule',
    'register.terms_preamble_p1': "GSA est une plateforme numerique specialisee dans la distribution, la valorisation et la commercialisation de ressources numeriques destinees a la creation de projets videoludiques. GSA exerce une activite hybride comprenant une activite de marketplace mettant en relation vendeurs et acheteurs, une activite de prestation de services lies a la presentation, la selection et la promotion des contenus, et une activite de creation et de fourniture de prestations professionnelles realisees directement par GSA.",
    'register.terms_preamble_p2': "Le present contrat regit les relations entre <strong>GSA Store</strong> (ci-apres GSA ou la Plateforme) et tout createur inscrit en qualite de vendeur (ci-apres le Vendeur). En creant un compte vendeur, le Vendeur accepte sans reserve l'integralite des presentes conditions ainsi que les Fondations Juridiques de GSA.",
    'register.terms_art1': 'Article 1 - Definitions',
    'register.terms_art1_p1': 'Les termes utilises dans le present contrat s'entendent au sens des Fondations Juridiques de GSA (version 1.0.0) :',
    'register.terms_art1_l1': '<strong>Produit numerique</strong> : tout contenu immateriel propose a la vente (modeles 3D, textures, environnements, maps, effets visuels, interfaces, sons, animations, ressources pour moteurs de jeux...) ;',
    'register.terms_art1_l2': '<strong>Validation GSA</strong> : processus interne de controle humain effectue avant publication - prestation de controle qualite, ne constituant ni certification technique absolue, ni garantie contre tout defaut, ni garantie de compatibilite ;',
    'register.terms_art1_l3': '<strong>Presentation GSA</strong> : miniatures, captures, videos, descriptions et textes promotionnels prepares par GSA, proteges au titre du droit d'auteur ;',
    'register.terms_art1_l4': '<strong>Commission</strong> : remuneration percue par GSA, definie contractuellement avec chaque Vendeur.',
    'register.terms_art2': 'Article 2 - Nature du role de GSA',
    'register.terms_art2_p1': "GSA agit en qualite d'operateur de plateforme permettant la mise en relation entre vendeurs et acheteurs. Sauf indication contraire, GSA n'est ni l'auteur des contenus proposes par les Vendeurs, ni le titulaire des droits attaches a ces contenus, ni le developpeur des produits commercialises par des tiers. Les obligations relatives au contenu vendu demeurent a la charge du Vendeur concerne.",
    'register.terms_art3': 'Article 3 - Obligations du Vendeur',
    'register.terms_art3_p1': 'Le Vendeur demeure responsable :',
    'register.terms_art3_l1': 'de la titularite des droits attaches aux contenus proposes (contenu original ou realise avec l'autorisation expresse des ayants droit) ;',
    'register.terms_art3_l2': 'de la conformite juridique des produits et du respect des licences tierces applicables ;',
    'register.terms_art3_l3': "de l'exactitude des informations fournies (descriptions, images, documentation) ;",
    'register.terms_art3_l4': 'de ne pas publier de contenu contraire aux lois, aux droits des tiers ou aux bonnes moeurs.',
    'register.terms_art4': 'Article 4 - Commission et paiements',
    'register.terms_art4_p1': "La Plateforme preleve une commission de <strong>25%</strong> sur le prix de chaque vente (20% pour les vendeurs partenaires), qui remunere notamment l'acces a la plateforme, la visibilite, la Validation GSA, la Presentation GSA, la gestion technique et le support de premier niveau. Les paiements sont traites exclusivement via Stripe : le Vendeur doit disposer d'un compte Stripe Connect actif pour recevoir ses fonds. Le montant net, apres deduction de la commission, est transfere dans les delais prevus par Stripe (generalement 2 a 7 jours ouvrés). Les frais de traitement Stripe (1,5% + 0,25 EUR par transaction) restent a la charge de la Plateforme.",
    'register.terms_art5': 'Article 5 - Propriete intellectuelle et licence de vente',
    'register.terms_art5_p1': "Le Vendeur conserve l'integralite des droits de propriete intellectuelle sur ses creations. Il concede a GSA une licence non exclusive lui permettant de representer, stocker et distribuer les creations dans le cadre strict de la vente. L'acheteur acquiert une Licence GSA : non exclusive, personnelle, non transferable, sans transfert de propriete et sans droit de redistribution. Sont notamment interdits sauf autorisation : la reproduction, la redistribution, la revente, la mise a disposition publique et l'exploitation commerciale non autorisee des contenus.",
    'register.terms_art6': 'Article 6 - Hierarchie contractuelle',
    'register.terms_art6_p1': "Les documents contractuels applicables sont : 1. Mentions legales ; 2. Conditions Generales d'Utilisation ; 3. Conditions Generales de Vente ; 4. Licence GSA ; 5. Contrat vendeur (present contrat) ; 6. Politiques complementaires. En cas de contradiction, le document specifique prevaut sur le document general. En cas de manquement grave aux presentes conditions, GSA se reserve le droit de suspendre ou supprimer le compte Vendeur. Le droit applicable est le droit francais.",
    'register.terms_cgv_title': '1. Conditions generales de vente (CGV)',
    'register.terms_cgv_p1': "Les presentes CGV regissent les achats effectues sur la Plateforme GSA Store. Toute commande implique l'acceptation des presentes conditions. Les prix sont affiches en euros, TTC. La Plateforme se reserve le droit de modifier ses prix a tout moment, les produits etant factures sur la base du tarif en vigueur au moment de la commande.",
    'register.terms_cgu_title': "2. Conditions generales d'utilisation (CGU)",
    'register.terms_cgu_p1': 'En utilisant la Plateforme, vous vous engagez a :',
    'register.terms_cgu_l1': 'Fournir des informations exactes lors de la creation de votre compte ;',
    'register.terms_cgu_l2': 'Ne pas porter atteinte aux droits des createurs (pas de redistribution, copie ou revente des creations telechargees) ;',
    'register.terms_cgu_l3': 'Ne pas publier de contenu illegal, frauduleux ou malveillant ;',
    'register.terms_cgu_l4': 'Ne pas contourner les systemes de paiement ou de protection de la Plateforme.',
    'register.terms_pay_title': '3. Paiement et livraison',
    'register.terms_pay_p1': "Les paiements sont securises et traites via Stripe. Apres validation du paiement, l'acces au telechargement de la creation est immediat dans votre espace Mes telechargements. En cas de paiement effectue mais non confirme, une verification automatique est effectuee et le produit est debloque des confirmation.",
    'register.terms_with_title': '4. Droit de retractation et remboursements',
    'register.terms_with_p1': "Conformement a l'article L221-28 du Code de la consommation, le droit de retractation ne s'applique pas aux contenus numeriques fournis immediatement et telecharges. Toutefois, en cas de produit non conforme ou non fonctionnel, le remboursement peut etre accorde sous 14 jours apres etude de la demande. Contactez le support via le vendeur ou la Plateforme.",
    'register.terms_ip_title': '5. Propriete intellectuelle',
    'register.terms_ip_p1': "Les creations restent la propriete de leurs auteurs. L'achat confere une licence d'utilisation personnelle, non transferable et non exclusive. Toute redistribution, revente ou copie du contenu telecharge est interdite.",
    'register.terms_data_title': '6. Protection des donnees',
    'register.terms_data_p1': 'Vos donnees personnelles sont traitees conformement au RGPD. Elles sont utilisees pour la gestion de votre compte, des commandes et de la relation client, et ne sont jamais revendues a des tiers.',
    'register.terms_liab_title': '7. Responsabilite et litiges',
    'register.terms_liab_p1': 'La Plateforme agit comme intermediaire technique entre vendeurs et acheteurs. En cas de litige, une solution amiable sera recherchee en priorite. Le droit applicable est le droit francais.',
"""

en = """    'register.seller': 'Seller',
    'register.join_desc': 'To register, you must be a member of the official GSA Discord server.',
    'register.join_retry': "I'm a member, register me",
    'register.verify_title': 'Verify your email',
    'register.verify_sub': 'A validation code was sent to <strong>{email}</strong>.',
    'register.devcode': 'Demo mode (email not configured) - your code:',
    'register.verify_code': 'Validation code',
    'register.verifying': 'Verifying...',
    'register.verify_btn': 'Validate my email',
    'register.with_discord_seller': 'Register as a seller with Discord',
    'register.with_discord': 'Register with Discord',
    'register.terms_title_seller': 'Seller contract',
    'register.terms_title': 'Terms and conditions',
    'register.terms_scroll': 'Scroll to the bottom to accept the terms.',
    'register.terms_docs': 'Documents to accept ({n}):',
    'register.terms_accept': 'I have read and accept all the documents above.',
    'register.terms_confirm': 'Confirm and continue',
    'register.terms_preamble': 'Preamble',
    'register.terms_preamble_p1': 'GSA is a digital platform specialized in the distribution, promotion and sale of digital resources for video game projects. GSA operates a hybrid activity including a marketplace connecting sellers and buyers, a service activity related to content presentation, selection and promotion, and a creation activity providing professional services delivered directly by GSA.',
    'register.terms_preamble_p2': 'This contract governs the relationship between <strong>GSA Store</strong> (hereafter GSA or the Platform) and any creator registered as a seller (hereafter the Seller). By creating a seller account, the Seller unreservedly accepts all of these terms as well as the GSA Legal Foundations.',
    'register.terms_art1': 'Article 1 - Definitions',
    'register.terms_art1_p1': 'The terms used in this contract have the meaning defined in the GSA Legal Foundations (version 1.0.0):',
    'register.terms_art1_l1': '<strong>Digital product</strong>: any intangible content offered for sale (3D models, textures, environments, maps, visual effects, interfaces, sounds, animations, game engine assets...) ;',
    'register.terms_art1_l2': '<strong>GSA Validation</strong>: internal human review process performed before publication - a quality control service, neither an absolute technical certification, nor a warranty against any defect, nor a compatibility guarantee ;',
    'register.terms_art1_l3': '<strong>GSA Presentation</strong>: thumbnails, screenshots, videos, descriptions and promotional texts prepared by GSA, protected by copyright ;',
    'register.terms_art1_l4': '<strong>Commission</strong>: remuneration received by GSA, defined contractually with each Seller.',
    'register.terms_art2': 'Article 2 - Nature of the role of GSA',
    'register.terms_art2_p1': 'GSA operates as a platform operator connecting sellers and buyers. Unless otherwise stated, GSA is neither the author of the content offered by Sellers, nor the owner of the rights attached to that content, nor the developer of products sold by third parties. Obligations relating to the sold content remain the responsibility of the relevant Seller.',
    'register.terms_art3': 'Article 3 - Seller obligations',
    'register.terms_art3_p1': 'The Seller remains responsible for:',
    'register.terms_art3_l1': 'ownership of the rights attached to the offered content (original content or made with the express permission of the rights holders) ;',
    'register.terms_art3_l2': 'legal compliance of the products and compliance with applicable third-party licenses ;',
    'register.terms_art3_l3': 'accuracy of the provided information (descriptions, images, documentation) ;',
    'register.terms_art3_l4': 'not publishing content that violates the law, third-party rights or public decency.',
    'register.terms_art4': 'Article 4 - Commission and payments',
    'register.terms_art4_p1': 'The Platform charges a commission of <strong>25%</strong> on the price of each sale (20% for partner sellers), which covers platform access, visibility, GSA Validation, GSA Presentation, technical management and first-level support. Payments are processed exclusively via Stripe: the Seller must have an active Stripe Connect account to receive funds. The net amount, after commission, is transferred within the timeframes set by Stripe (usually 2 to 7 business days). Stripe processing fees (1.5% + EUR 0.25 per transaction) are borne by the Platform.',
    'register.terms_art5': 'Article 5 - Intellectual property and sales license',
    'register.terms_art5_p1': 'The Seller retains all intellectual property rights on their creations. They grant GSA a non-exclusive license to represent, store and distribute the creations strictly for the purpose of the sale. The buyer acquires a GSA License: non-exclusive, personal, non-transferable, without ownership transfer and without redistribution rights. Unless authorized, the following are prohibited: reproduction, redistribution, resale, public availability and unauthorized commercial exploitation of the content.',
    'register.terms_art6': 'Article 6 - Contractual hierarchy',
    'register.terms_art6_p1': 'The applicable contractual documents are: 1. Legal notices; 2. Terms of Use; 3. Terms of Sale; 4. GSA License; 5. Seller contract (this contract); 6. Additional policies. In case of contradiction, the specific document prevails over the general document. In case of serious breach of these terms, GSA reserves the right to suspend or delete the Seller account. Applicable law is French law.',
    'register.terms_cgv_title': '1. Terms of Sale (CGV)',
    'register.terms_cgv_p1': 'These Terms of Sale govern purchases made on the GSA Store Platform. Any order implies acceptance of these terms. Prices are shown in euros, incl. VAT. The Platform reserves the right to change its prices at any time, products being invoiced at the rate in force at the time of the order.',
    'register.terms_cgu_title': '2. Terms of Use (CGU)',
    'register.terms_cgu_p1': 'By using the Platform, you agree to:',
    'register.terms_cgu_l1': 'Provide accurate information when creating your account ;',
    'register.terms_cgu_l2': 'Not infringe creators rights (no redistribution, copying or resale of downloaded creations) ;',
    'register.terms_cgu_l3': 'Not publish illegal, fraudulent or malicious content ;',
    'register.terms_cgu_l4': 'Not bypass the payment or protection systems of the Platform.',
    'register.terms_pay_title': '3. Payment and delivery',
    'register.terms_pay_p1': 'Payments are secured and processed via Stripe. After payment validation, access to the download of the creation is immediate in your My downloads area. If a payment was made but not confirmed, an automatic check is performed and the product is unlocked upon confirmation.',
    'register.terms_with_title': '4. Right of withdrawal and refunds',
    'register.terms_with_p1': "Under Article L221-28 of the French Consumer Code, the right of withdrawal does not apply to digital content delivered immediately and downloaded. However, in case of a non-compliant or non-functional product, a refund may be granted within 14 days after review of the request. Contact support via the seller or the Platform.",
    'register.terms_ip_title': '5. Intellectual property',
    'register.terms_ip_p1': 'Creations remain the property of their authors. The purchase grants a personal, non-transferable and non-exclusive license. Any redistribution, resale or copy of the downloaded content is prohibited.',
    'register.terms_data_title': '6. Data protection',
    'register.terms_data_p1': 'Your personal data is processed in accordance with the GDPR. It is used for account, order and customer relationship management, and is never sold to third parties.',
    'register.terms_liab_title': '7. Liability and disputes',
    'register.terms_liab_p1': 'The Platform acts as a technical intermediary between sellers and buyers. In case of dispute, an amicable solution will be sought first. Applicable law is French law.',
"""

a_fr = "    'register.login_link': 'Se connecter',"
a_en = "    'register.login_link': 'Sign in',"
assert s.count(a_fr) == 1, "ancre fr register"
assert s.count(a_en) == 1, "ancre en register"
s = s.replace(a_fr, a_fr + "\n" + fr, 1)
s = s.replace(a_en, a_en + "\n" + en, 1)
io.open(p, "w", encoding="utf-8", newline="").write(s)
print("cles register ajoutees (fr+en)")
